### ISSUE TITLE
Cant connect to redis-server

### ISSUE THREAD

**Issue by kristianwestg** [redis/RedisDesktopManager#4944] opened 2020-11-25 08:11 UTC
Cant connect to redis server. Version 2020.6.142 (from App Store) on macOS Big Sur. Connecting to an public redis-server with SSL. 

Log message: 
Connection: Disconnect on error: Connection error: Error during SSL handshake: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

![Screenshot 2020-11-25 at 08 41 41](https://user-images.githubusercontent.com/60093376/100197148-345ace00-2efa-11eb-9a61-e1aa13bfeec8.png)

Keys verified with redis-cli
![Screenshot 2020-11-25 at 09 05 36](https://user-images.githubusercontent.com/60093376/100199539-9c5ee380-2efd-11eb-8e6f-b4e673a1884f.png)

**Comment by uglide** [comment] 2020-11-25 14:34
Looks like issue #4857 is reproducible again. I'm investigating why.

Thanks for the bug report.

**Comment by kristianwestg** [comment] 2021-02-09 08:30
Update on version 2021.2.161, same settings as above. Log message:

"Connection: Disconnect on error: Connection error: Error during SSL handshake: "

Server side log message:
"Error accepting a client connection: error:1417C0C7:SSL routines:tls_process_client_certificate:peer did not return a certificate"

**Comment by uglide** [comment] 2021-02-18 07:00
@kristianwestg this issue was resolved in 2021.2.173 (AppStore).
Please let me know if it works for you.

**Comment by kristianwestg** [comment] 2021-02-19 06:18
Yes, it working! Thank you!

**Comment by uglide** [comment] 2021-02-19 08:47
Great! Thanks for the update!

**Closed as completed by uglide** 2021-02-19 08:47 UTC
Labels: bug, waiting for feedback
