### ISSUE TITLE
Support Delete of multiple keys

### ISSUE THREAD

**Issue by gopi-ar** [redis/RedisDesktopManager#3364] opened 2015-06-11 03:22 UTC
It's great that rdm groups similar keys by `:`. What would be awesome is the ability to delete all children belonging to this node easily. For e.g., if I have 2 keys `A:12`, `A:13`, RDM groups them both under `A`. It would be nice to be able to delete all items under `A` in a single go.

**Comment by uglide** [comment] 2015-06-11 09:31
Duplicate of #89

**Closed as completed by uglide** 2015-06-11 09:31 UTC
Labels: duplicate
