### ISSUE TITLE
Connection List become weird

### ISSUE THREAD

**Issue by doggy8088** [redis/RedisDesktopManager#5216] opened 2022-03-18 14:08 UTC
**Describe the bug**

Randomly appear weird list. Please see the screenshot.

**To Reproduce**
1. Open RESP.app
2. Add Connection
3. Connect to the Redis Server
4. See screenshot

**Expected behavior**

It works for days. It's just happen today.

**Screenshots**

![image](https://user-images.githubusercontent.com/88981/159017731-f0ac76c2-8e94-432b-9c83-48481d407a38.png)

**Environment (please complete the following information):**
 - OS & version: `Microsoft Windows [Version 10.0.19043.1586]`
 - Redis-Server version: `6.0.14`

**Additional context**

N/A

**Comment by uglide** [comment] 2022-03-18 15:56
I'm trying to catch this random bug. It looks like a race condition in the model update. If you will notice any context or additional clues about what leads to this bug - please share it here. Thanks!

**Comment by uglide** [comment] 2022-07-28 12:13
Duplicate of #5163

**Closed as completed by uglide** 2022-07-28 12:13 UTC
Labels: bug
