### ISSUE TITLE
add readonly mode

### ISSUE THREAD

**Issue by ZZMarquis** [redis/RedisDesktopManager#3851] opened 2017-06-08 03:35 UTC
RDM Version: 0.9.0.559<br>
Environment (OS name and version): Windows<br>
Redis Server Version: 2.8.2<br>

Thank you for your contribution.

I would like to suggest that: add readonly mode for RDM. most of time, we just want to read or review the data in redis, but does not want to modify it.  in order to prevent wrong operation, I think RDM can add readonly mode.

**Comment by uglide** [comment] 2017-09-14 09:13
Duplicate of #3771

**Closed as completed by uglide** 2017-09-14 09:13 UTC
Labels: duplicate
