### ISSUE TITLE
RDM do not support asian language keys in NS names

### ISSUE THREAD

**Issue by zjufish** [redis/RedisDesktopManager#3695] opened 2016-08-29 11:12 UTC
RDM Version: <br>
Environment (OS name and version): <br>
Redis Server Version: <br>

Steps to reproduce:
1. Add namespaced key with UTF chars
2. Load database keys

Expected result: 
correct display the Asian language, e.g. Chinese

Actual Result: 
messy stuff displayed in node

**Comment by uglide** [comment] 2016-08-29 11:18
@zjufish Could you please specify more details about how  to reproduce this problem?

Because on my env it works just fine:
![image](https://cloud.githubusercontent.com/assets/1655867/18049848/70adc7b2-6df3-11e6-99f6-fd419fc77c72.png)

**Comment by uglide** [comment] 2016-08-29 11:21
Ok, looks like I've reproduced your problem
![image](https://cloud.githubusercontent.com/assets/1655867/18049903/d5039ade-6df3-11e6-9bb7-0a13d961b473.png)

**Comment by uglide** [comment] 2016-09-09 13:31
Fixed in 0.9.0-alpha1

**Closed as completed by uglide** 2016-09-09 13:31 UTC
Labels: bug, major

**Comment by zjufish** [comment] 2016-10-03 06:23
chinese has different encodings. GBK/Unicode for example.
i believe in your snapshot it is using gbk. if you try unicode you will see
what i mean. attached a pic.

**Comment by zjufish** [comment] 2016-10-03 06:26
ideally i hope it can support a encoding config option to display different
encoded asia languages.

**Comment by zjufish** [comment] 2016-10-03 06:29
for emaple, on windows platform you may want to use this
https://msdn.microsoft.com/en-us/library/windows/desktop/dd319072(v=vs.85).aspx
