### ISSUE TITLE
Show error message when SCAN command failed

### ISSUE THREAD

**Issue by southwolf** [redis/RedisDesktopManager#3445] opened 2015-08-20 07:12 UTC
Version: 0.8.3840 & 3835
Environment: Windows 7 SP1 x64 & Windows 10 x64
Redis Server Version: 2.8.14

Steps to reproduce:
1.Connect to my redis server
2.Click on connection, and click db0

Expected result: all keys

Actual Result: nothing.

But when I opened console inside RedisDesktopManager and input "KEYS *", all keys were displayed correctly.

**Comment by uglide** [comment] 2015-08-20 07:54
Duplicate of #3407

Please check 'Keys glob pattern' in connections settings (advanced settings tab)

**Comment by southwolf** [comment] 2015-08-20 08:02
Thank you @uglide for the reply. But I checked  'Keys glob pattern' , it is set to '*', and 'Namespace separator' set to ':'. Still got empty response. This bug occurs only on certain server, while other redis servers got correct data.

**Comment by uglide** [comment] 2015-08-20 08:26
@southwolf Could you paste log from 'system log' tab in RDM?

**Comment by southwolf** [comment] 2015-08-20 08:31
A successful connection

```
2015-08-20 16:30:27 : Click on tree item: 2
2015-08-20 16:30:27 : Connection: AUTH
2015-08-20 16:30:27 : Connection: 192.168.1.46 > connected
2015-08-20 16:30:27 : Connection: 192.168.1.46 > [runCommand] ping
2015-08-20 16:30:27 : Connection: 192.168.1.46 > [runCommand] ping -> response received : 0
2015-08-20 16:30:27 : Connection: 192.168.1.46 > [runCommand] INFO
2015-08-20 16:30:27 : Connection: 192.168.1.46 > [runCommand] INFO -> response received : 0
2015-08-20 16:30:27 : Connection: AUTH OK
2015-08-20 16:30:27 : Connection: 192.168.1.46 > [runCommand] info
2015-08-20 16:30:27 : Connection: 192.168.1.46 > [runCommand] info -> response received : 0
2015-08-20 16:30:27 : Click on tree item: 2
2015-08-20 16:30:28 : Click on tree item: 0
2015-08-20 16:30:28 : Connection: 192.168.1.46 > [runCommand] select 0
2015-08-20 16:30:28 : Connection: 192.168.1.46 > [runCommand] select 0 -> response received : 0
2015-08-20 16:30:28 : Connection: 192.168.1.46 > [runCommand] scan 0 MATCH * COUNT 10000
2015-08-20 16:30:28 : Connection: 192.168.1.46 > [runCommand] scan 0 MATCH * COUNT 10000 -> response received : 2
2015-08-20 16:30:28 : Click on tree item: 0
```

A connection with an empty 'db0'

```
2015-08-20 16:30:12 : Click on tree item: 0
2015-08-20 16:30:12 : Connection: AUTH
2015-08-20 16:30:12 : Connection: XXX > connected
2015-08-20 16:30:12 : Connection: XXX > [runCommand] ping
2015-08-20 16:30:12 : Connection: XXX > [runCommand] ping -> response received : 0
2015-08-20 16:30:12 : Connection: XXX > [runCommand] INFO
2015-08-20 16:30:12 : Connection: XXX > [runCommand] INFO -> response received : 0
2015-08-20 16:30:12 : Connection: AUTH OK
2015-08-20 16:30:12 : Connection: XXX > [runCommand] info
2015-08-20 16:30:12 : Connection: XXX > [runCommand] info -> response received : 0
2015-08-20 16:30:12 : Click on tree item: 0
2015-08-20 16:30:14 : Click on tree item: 0
2015-08-20 16:30:14 : Connection: XXX > [runCommand] select 0
2015-08-20 16:30:14 : Connection: XXX > [runCommand] select 0 -> response received : 0
2015-08-20 16:30:14 : Connection: XXX > [runCommand] scan 0 MATCH * COUNT 10000
2015-08-20 16:30:14 : Connection: XXX > [runCommand] scan 0 MATCH * COUNT 10000 -> response received : 0
```

**Comment by uglide** [comment] 2015-08-20 09:14
@southwolf Which differences do you have between this to redis-servers?

**Comment by southwolf** [comment] 2015-08-20 09:19
@uglide The failed connection is a cloud-based Redis server. You can try that: XXXX. The other one is a local Redis.

**Comment by uglide** [comment] 2015-08-20 09:30
@southwolf 

I have following:

```
XXXX:0> scan 0 MATCH * COUNT 10000
ERR protocol is not supported 
```

**Comment by uglide** [comment] 2015-08-20 09:32
Looks like RDM should fallback to keys even on 2.8 if SCAN failed

**Comment by southwolf** [comment] 2015-08-20 09:34
Thank you @uglide, maybe the cloud Redis supplier disables SCAN command?

**Comment by uglide** [comment] 2015-08-20 09:35
@southwolf 
Yes, SCAN is disabled. Which cloud do you use?

**Comment by southwolf** [comment] 2015-08-20 09:36
XXX, a Chinese cloud computing supplier

**Comment by uglide** [comment] 2015-08-20 09:41
@southwolf Thanks for the feedback! It's very usefull. I will improve error handling in such cases and implement additonal advanced option - 'Enforce usage of KEYS command instead of SCAN'

**Closed as completed** 2015-08-23 15:30 UTC
Labels: bug, major
