### ISSUE TITLE
Application cannot start (0xc000007b). Click OK to close the application

### ISSUE THREAD

**Issue by larkwins** [redis/RedisDesktopManager#3831] opened 2017-04-22 03:47 UTC
RDM Version: 0.8.8

Environment (OS name and version): WIN7

Redis desktop manager alerts when opened:

> Application cannot start (0xc000007b). Click OK to close the application.

How to deal with this case?

PS: DirectX 9.0 has been installed successfully.

**Comment by ghost** [comment] 2017-04-24 13:41
都是英文问题，你这写个汉语谁看的懂啊

**Comment by larkwins** [comment] 2017-04-25 05:15
@Umbraller 

help

**Comment by uglide** [comment] 2017-04-28 15:23
Looks like duplicate of #3805

**Closed as completed by uglide** 2017-04-28 15:23 UTC
Labels: duplicate

**Comment by larkwins** [comment] 2017-05-10 06:58
@uglide but it hasn`t been solved yet, any ideas?
