### ISSUE TITLE
RDM - 9.x Not connecting when Encryption in-transit &Encryption at-rest enabled

### ISSUE THREAD

**Issue by samrajcse** [redis/RedisDesktopManager#4008] opened 2018-02-15 10:37 UTC
RDM Version: 0.9.0.684
Environment (OS name and version): Windows 2012
Redis Server Version: AWS Redis 3.2.6

Steps to reproduce:

1. Create a redis in AWS with Encryption in-transit & Encryption at-rest enabled.

2. Copy the node url and try to connect with 0.9.0 RDM with SSL enabled. Its failing.

3. Now try with 0.8.x version. Its connecting properly.

Expected result: Connection should work fine

Actual Result: Its not connecting

**Comment by uglide** [comment] 2018-02-19 09:56
Looks like duplicate of #3980

**Closed as completed by uglide** 2018-02-19 09:56 UTC
Labels: duplicate
