### ISSUE TITLE
RDM 0.9.0-alpha2 crash when executing test connections

### ISSUE THREAD

**Issue by immatt2015** [redis/RedisDesktopManager#3760] opened 2016-11-02 15:06 UTC
RDM Version: 0.9.0-alpha2
Environment (OS name and version): OSX 10.12.1 
Redis Server Version: <br>

Steps to reproduce:

1.  click settings button

2. click `Test Connction`

3. the program can not work well.

Expected result: 
does not work
Actual Result: 
show the result

**Comment by jtr109** [comment] 2017-01-13 02:56
The app is awesome! Thanks a lot.

However, the issue still happend in 0.9.0.41, which installed by the dmg file downloaded from [release page](https://github.com/uglide/RedisDesktopManager/releases/tag/0.9.0-alpha3) with version 0.9.0-alpha3.

It crashes if I clicked `Test Connection`. The application can only be force quit. But it works well and the information of my target redis can be showed if `OK` clicked. 

My kernal version: Darwin Kernel Version 15.6.0

BTW, the text of tabs cannot exhibits completely in the window after `Connect to Redis Server` being clicked, such as "Connection Settings", "Advanced Settings".

**Comment by uglide** [comment] 2017-03-29 08:41
Duplicate of https://github.com/uglide/RedisDesktopManager/issues/3760

**Closed as completed by uglide** 2017-03-29 08:41 UTC
Labels: duplicate
