### ISSUE TITLE
Need previous version is no cache.

### ISSUE THREAD

**Issue by uopeydel** [redis/RedisDesktopManager#4035] opened 2018-03-02 04:43 UTC
RDM Version: 9^
Environment (OS name and version): window 10
Redis Server Version: lasted

Steps to reproduce:

1. Install rdm .

2. Alway cache when connect , setting else.

3. My old pc is have redis desktop manager 0.8.8.384  but i already delete install file , that version is work and i can't find that version for download.

Expected result: Can download previous version is work.

Actual Result: Can use rdm without promblem.

**Comment by uglide** [comment] 2018-03-02 13:41
Possible duplicate of #4026

**Closed as completed by uglide** 2018-03-02 13:41 UTC
Labels: duplicate
