### ISSUE TITLE
No support for binary keys

### ISSUE THREAD

**Issue by ThreadedThinking** [redis/RedisDesktopManager#2454] opened 2014-08-31 01:14 UTC
I am using MAC addresses as keys, however I am not using the literal notation such as 

11:22:33:44:55:66

I am storing the raw 6 bytes as the key instead of the inflated 17 byte version. I get an error when selecting the key(looks blank) "Can not load key value. Key was removed or redis server went away."

**Comment by uglide** [comment] 2014-09-19 16:17
Duplicate of #2228

**Closed as completed by uglide** 2014-09-19 16:17 UTC
Labels: major
