### ISSUE TITLE
Windows 10 GUI Display Issues

### ISSUE THREAD

**Issue by devonzara** [redis/RedisDesktopManager#3923] opened 2017-10-19 01:29 UTC
**RDM Version:** <br>0.9.0-alpha5
**Environment (OS name and version):** <br>Windows 10 Version 1703 (Build 15063.674)
**Redis Server Version:** <br>Irrelevant
**GPU:** <br>Nvidia GeForce GTX 760
**Driver:** <br>Nvidia v387.92
**Display:** <br>Dell U2415, 1920 x 1200 at 60Hz (~94 PPI)

I'm experiencing some issues with the placement of form elements on Windows 10... 

![image](https://user-images.githubusercontent.com/1634972/31749857-7b987372-b44a-11e7-8b9b-72c6f423f087.png)

![image](https://user-images.githubusercontent.com/1634972/31749865-81c3f0b4-b44a-11e7-854a-f576f4f7cb8a.png)

![image](https://user-images.githubusercontent.com/1634972/31749871-8641e308-b44a-11e7-9b40-1aefc17e2d93.png)

![image](https://user-images.githubusercontent.com/1634972/31749983-32b1ce78-b44b-11e7-9c93-2a11c1fa5bff.png)

**Comment by uglide** [comment] 2017-10-26 09:08
Duplicate of https://github.com/uglide/RedisDesktopManager/issues/3876

**Closed as completed by uglide** 2017-10-26 09:08 UTC
Labels: duplicate
