### ISSUE TITLE
Hope the connections can be divided by group

### ISSUE THREAD

**Issue by firstmetcs** [redis/RedisDesktopManager#4877] opened 2020-08-17 02:56 UTC
The RDM now can only add connections and cannot classify connections by group. Hope can add the feature that allows us to divide the connections into a group.

Such as Navicat:

<img width="256" alt="image" src="https://user-images.githubusercontent.com/32634443/90353221-51b90a00-e078-11ea-9985-bc42efcf1ab6.png">

**Comment by uglide** [comment] 2020-09-07 13:40
Duplicate of #3367

**Closed as completed by uglide** 2020-09-07 13:40 UTC
