### ISSUE TITLE
“rdm.app” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by DragonBe** [redis/RedisDesktopManager#3935] opened 2017-11-27 12:01 UTC
RDM Version: 0.8.8
Environment (OS name and version): Mac OS X macOS Sierra 0.12.6
Redis Server Version: 2.8.17

Steps to reproduce:

1. Purchase app

2. Download and install app

3. Start app by double clicking on it or use command line `open -a rdm.app`

Expected result: 

A working application

Actual Result: 

Getting a pop-up stating **“rdm.app” can’t be opened because it is from an unidentified developer.**

![image](https://user-images.githubusercontent.com/282825/33265703-fad75210-d372-11e7-9444-c8cff5f0556c.png)

**Comment by uglide** [comment] 2017-11-27 13:58
Duplicate of #3655

**Closed as completed by uglide** 2017-11-27 13:58 UTC
