### ISSUE TITLE
search option stop working on 0.9.1

### ISSUE THREAD

**Issue by YohaiAllouche** [redis/RedisDesktopManager#4063] opened 2018-03-27 05:07 UTC
RDM Version: <br>
Environment (OS name and version): <br>
Redis Server Version: <br>

Steps to reproduce:

1. install version 0.9.1

2. try to search a key like in the previous version

Expected result:  key will be found

Actual Result: nothing found even it exists

**Comment by uglide** [comment] 2018-04-04 15:20
Duplicate of #4060

**Closed as completed by uglide** 2018-04-04 15:20 UTC
Labels: duplicate
