### ISSUE TITLE
When the RDM looks at the JSON schema, the accuracy of the view's long type count is lost.But viewing it in plain text mode is normal

### ISSUE THREAD

**Issue by yanyl001** [redis/RedisDesktopManager#5035] opened 2021-04-19 01:02 UTC
![image](https://user-images.githubusercontent.com/24784196/115168535-e4211a00-a0ed-11eb-8e3c-416d205deae0.png)

**Comment by uglide** [comment] 2021-04-19 09:40
Hello, thanks for the bug report but this issue is a duplicate of #4964

**Closed as completed by uglide** 2021-04-19 09:40 UTC
Labels: bug
