### ISSUE TITLE
View as JSON do not refresh and not well format

### ISSUE THREAD

**Issue by ferrazp** [redis/RedisDesktopManager#3848] opened 2017-06-06 13:06 UTC
RDM Version: 0.9.0.559<br>
Environment (OS name and version): Windows 7 x64<br>
Redis Server Version: 3.2.100<br>

Steps to reproduce:

1. Click on a key and view a JSON value as Plain Text

2. Change view to JSON

3. Check

Expected result: JSON formatted value

Actual Result: The same plain text formatted value

**Comment by uglide** [comment] 2017-09-14 09:07
Duplicate of #3901

**Closed as completed by uglide** 2017-09-14 09:07 UTC
Labels: duplicate
