### ISSUE TITLE
Key name truncation.

### ISSUE THREAD

**Issue by LoreTru** [redis/RedisDesktopManager#3478] opened 2015-09-25 15:34 UTC
Version: 0.8.0.3841
Environment: Windows 7 SP1 x64
Redis Server Version: 2.8.1

Steps to reproduce:
1.create a key like this: FirstLevelString:SecondLevelString:ThirdLevelString:MY_KEY
2. The keys explorer will truncate the last element of the tree. I'm not able to read the MY_KEY name.

![bug](https://cloud.githubusercontent.com/assets/14839321/10104649/132f4b90-63ab-11e5-9bfc-8f142583134a.jpg)

**Comment by uglide** [comment] 2015-09-26 03:49
Hello @LoreTru 
This issue is duplicate of #3456 which is already fixed and will be available in 0.8.0-release. Thanks!

**Closed as completed by uglide** 2015-09-26 03:49 UTC
Labels: duplicate
