### ISSUE TITLE
RDM crashed when redis-server's configure file is incorrect.

### ISSUE THREAD

**Issue by taobig** [redis/RedisDesktopManager#3808] opened 2017-02-20 09:39 UTC
RDM Version:  0.8.8.384<br>
Environment (OS name and version): Windows 10 X86_64<br>
Redis Server Version: 3.2.8<br>

Steps to reproduce:

1. comment out  all `bind` directive in redis configure file.

2. connect to redis server with RDM(without `Test Connection`,just save this connection; and then double click left button to open this connection)

Expected result: 
 give me some error message.
Actual Result: 
  RDM crashed!

**from remote client:**
192.168.x.xxx:6379> keys *
(error) DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.

**Comment by uglide** [comment] 2017-04-28 15:26
Duplicate of https://github.com/uglide/RedisDesktopManager/issues/3780

**Closed as completed by uglide** 2017-04-28 15:26 UTC
Labels: duplicate
