### ISSUE TITLE
Redis GUI elements unable to resize properly on hi-res screens

### ISSUE THREAD

**Issue by DavidHSell** [redis/RedisDesktopManager#3602] opened 2016-03-15 16:02 UTC
RDM Version: 0.8.3850 <br>
Environment (Windows 10): <br>
Redis Server Version: <br>

Steps to reproduce:
1. ... With a high res laptop screen (3200x1800, 13") Windows 10 recommends a 250% increase in all GUI elements, intending to affect all Windows apps.  As main screen, launch the Redis Desktop Manager.
2. ... Application will launch, but some GUI elements fail to expand by 250%, resulting in teeny tiny GUI elements.
3. ... Application is unusable in this mode.

Expected result: GUI elements should resize and increase to match everything else on screen.

Actual Result: GUI elements too small to see properly.
![redisresized](https://cloud.githubusercontent.com/assets/17460205/13784463/5cd6cc40-ea9d-11e5-8bde-b3f8e15e444d.png)

P.S. I have a workaround if I use an external monitor that is scaled to 100%, and make it my main display, Redis Desktop Manager will load normally.

**Comment by yogaraptor** [comment] 2016-03-25 15:43
Same issue here on my hires Ubuntu laptop (Asus Zenbook 305CA). Guessing this is a QT issue?

**Comment by DavidHSell** [comment] 2016-03-25 15:47
Guessing so... Does the workaround work for you?

**Comment by yogaraptor** [comment] 2016-03-25 15:49
I don't have an external monitor to hand just now, but I would have thought so. If I set my laptop's screen to 1920x1080 then RDM displays fine.

**Comment by uglide** [comment] 2016-04-25 10:31
Duplicate of  #2506

**Closed as completed by uglide** 2016-04-25 10:31 UTC
Labels: duplicate

**Comment by markybry** [comment] 2017-12-06 09:53
Is there any progress on this issue?
