### ISSUE TITLE
RDM runs with 100% CPU core utilization

### ISSUE THREAD

**Issue by bp74** [redis/RedisDesktopManager#3504] opened 2015-10-15 08:02 UTC
After updating to RMD 0.8 (i'm not sure if this happened in an earlier version, but at least i didn't notice it) one CPU core runs constantly at 100% utilization. This happens as soon as you connect to a redis server (it does not run with 100% before connecting to a redis server).

OS: Windows 7

**Comment by mohitkhanna** [comment] 2015-10-15 09:36
Same here. Never saw this before with rdm. Is it related to rdm running in El Capitan? Screenshot attached.

<img width="1351" alt="rdm_high_cpu_el_capitan" src="https://cloud.githubusercontent.com/assets/681244/10510061/3dbccf06-734e-11e5-8f25-3eef394d29c0.png">

**Comment by simonwalton** [comment] 2015-10-16 18:35
I get the same in El Capitan. 100% CPU upon connecting to a server. You don't have to expand the tree or anything. I can confirm that the issue does not exist in the RC4 build for me.

**Comment by uglide** [comment] 2015-10-17 18:20
Hello folks! Thanks for the feedback, I will update my mb to El Capitan and try to reproduce this issue. I think version with fix will be delivered soon.

**Comment by tisswb** [comment] 2015-10-19 07:28
I have same problem. OS:windows 7

**Comment by glampr** [comment] 2015-10-19 15:19
Same problem with RDM 0.8.0-2544 on El Capitan.

**Comment by mellonedain** [comment] 2015-10-22 06:51
The same problem on Windows 10

**Comment by shaldev** [comment] 2015-10-22 10:46
Also on linux - Ubuntu 14.04

**Comment by dchernokur** [comment] 2015-10-22 14:42
Same issue on El Cap 10.11.1, but it only eats 25% of cpu

**Comment by jquacinella** [comment] 2015-10-22 17:33
+1, starts up fine but as soon as I connect, it starts grabbing up CPU. Any thoughts on the underlying cause? 

UPDATE: linux, Ubuntu 14.04

Would an strace help?

**Comment by Passerby** [comment] 2015-10-23 02:32
+1

**Comment by uglide** [comment] 2015-10-23 05:28
Fixed and will be released soon.

**Closed as completed by uglide** 2015-10-23 05:28 UTC
Labels: bug, Critical

**Comment by mohitkhanna** [comment] 2015-10-29 12:49
@uglide +1. The fix works!

**Comment by Somebi** [comment] 2018-12-12 09:52
It seems it's not. Latest version have the same issue. 100% CPU usage.
It seems it's not loading CPU right away, after some time. Just keep it opened and then realized it's eating a lot of CPU, because even my keyboard started to freeze...
Maybe you have some background processes?

**Comment by uglide** [comment] 2018-12-12 09:54
@somebi
Could you provide more details?
RDM version, OS and version, steps to reproduce. Thanks!

**Comment by Somebi** [comment] 2018-12-12 10:10
RedisDesktopManager 0.9.9-a99cd0c
Ubuntu 16.04

Can't currently reproduce myself. If i'll stop this again, i'll try to describe. Currently only opened a hash, which is updated by my soft.
Do you track hash updates from remote redis server on time basis? Maybe there is problem with that?

If update is very big, maybe you should throttle.

**Comment by Somebi** [comment] 2018-12-12 10:10
Because my hash is updating pretty rapidly.
