### ISSUE TITLE
Chinese can not show, messy code

### ISSUE THREAD

**Issue by whg517** [redis/RedisDesktopManager#4905] opened 2020-09-29 03:46 UTC
**Describe the bug**
When you open the window, most text areas except English display several small boxes. Chinese cannot be displayed.

**To Reproduce**

1. install snap
2. snap install redis-desktop-manager
3. /snap/bin/redis-desktop-manager.rdm

**Expected behavior**

Text should display normally

**Screenshots**

[![](http://qiniu.iclouds.work/FkpiUb-F_vLsnW_PfyHNeeLIKvgT.jpg)](http://qiniu.iclouds.work/FkpiUb-F_vLsnW_PfyHNeeLIKvgT.jpg)

```
 ✘ kevin@kevin  ~  /snap/bin/redis-desktop-manager.rdm
Disable auto-scaling
App font: "Open Sans" 11
Values font: "Ubuntu Mono"
Could not create AF_NETLINK socket (Operation not permitted)
Could not create AF_NETLINK socket (Operation not permitted)
Could not create AF_NETLINK socket (Operation not permitted)
("zh-CN")
Detected locale: "zh_CN"
Load translations file for locale: "zh_CN"
Could not create AF_NETLINK socket (Operation not permitted)
Could not create AF_NETLINK socket (Operation not permitted)
qrc:/LogView.qml:18:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/app.qml:395:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
qrc:/connections-tree/BetterTreeView.qml:242:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/app.qml:193:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/app.qml:185:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/app.qml:176:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/bulk-operations/BulkOperationsDialog.qml:350:25: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/app.qml:163:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/app.qml:157:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/value-editor/AddKeyDialog.qml:87:21: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/value-editor/editors/MultilineEditor.qml:464:21: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/value-editor/editors/MultilineEditor.qml:464:21: QML Connections: Cannot assign to non-existent property "onError"
qrc:/value-editor/editors/MultilineEditor.qml:464:21: QML Connections: Cannot assign to non-existent property "onValueUpdated"
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
qrc:/value-editor/editors/MultilineEditor.qml:426: ReferenceError: isMultiRow is not defined
qrc:/value-editor/editors/MultilineEditor.qml:465: ReferenceError: keyTab is not defined
qrc:/value-editor/editors/MultilineEditor.qml:358: ReferenceError: isMultiRow is not defined
qrc:/value-editor/editors/MultilineEditor.qml:357: ReferenceError: isMultiRow is not defined
Rendering backend: "software"
qml: Embedded formatters: [binary,cbor,msgpack,php,pickle]
qrc:/bulk-operations/BulkOperationsDialog.qml:13: TypeError: Cannot read property 'operationName' of null
qrc:/bulk-operations/BulkOperationsDialog.qml:418: TypeError: Cannot read property 'operationProgress' of null
qrc:/bulk-operations/BulkOperationsDialog.qml:262: TypeError: Cannot call method 'multiConnectionOperation' of null
qrc:/bulk-operations/BulkOperationsDialog.qml:226: TypeError: Cannot read property 'keyPattern' of null
qrc:/bulk-operations/BulkOperationsDialog.qml:165: TypeError: Cannot read property 'dbIndex' of null
qrc:/bulk-operations/BulkOperationsDialog.qml:153: TypeError: Cannot read property 'connectionName' of null
qrc:/value-editor/editors/MultilineEditor.qml:515: TypeError: Cannot call method 'isBinaryString' of null
qrc:/value-editor/editors/MultilineEditor.qml:324: TypeError: Cannot call method 'compressionAlgName' of null
qrc:/value-editor/editors/MultilineEditor.qml:318: TypeError: Cannot call method 'binaryStringLength' of null
qrc:/value-editor/editors/MultilineEditor.qml:350: TypeError: Cannot call method 'binaryStringLength' of null
qrc:/value-editor/editors/MultilineEditor.qml:537: TypeError: Cannot call method 'isBinaryString' of null

```

**Environment (please complete the following information):**

- os: `Deepin 20 (Base Debian)`
- snap: `2.37.4-1+b1`
- kernel: `5.4.50-amd64-desktop`

**Additional context**

I add `Open sans` and `Unbutn mono` front from [google fonts](https://fonts.google.com/) , and execute `fc-cache -fv`. But it can not work fine.

Someone can help me ? Thanks very much.

**Comment by uglide** [comment] 2020-10-01 09:52
It's duplicate of #4826

**Closed as completed by uglide** 2020-10-01 09:52 UTC
Labels: bug, snapcraft
