### ISSUE TITLE
no rule to process file

### ISSUE THREAD

**Issue by UnaHe** [redis/RedisDesktopManager#4111] opened 2018-05-04 16:09 UTC
RDM Version: 0.9.3
Environment (OS name and version): MAC OS 10.13.4
Redis Server Version:  4.0.9

Xcode Version: 9.3
Qt version Version : 5.10.1
Qt Creator Version : 4.5.1

Error encountered at compile time.
English is not translated well, hope to get help.

The complete process:
cd ./src/ && ./configure
Warning: coreutils 8.29 is already installed and up-to-date
To reinstall 8.29, run `brew reinstall coreutils`
=== BUILD TARGET breakpadUtilities OF PROJECT Breakpad WITH CONFIGURATION Release ===
warning: no rule to process file '/Users/una/item/rdm/3rdparty/gbreakpad/src/common/mac/arch_utilities.h' of type sourcecode.c.h for architecture x86_64
=== BUILD TARGET crash_report_sender OF PROJECT Breakpad WITH CONFIGURATION Release ===
/* com.apple.ibtool.document.notices */
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/Breakpad.xib:116: note: View is clipping its content
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/Breakpad.xib:66: note: View is clipping its content
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/Breakpad.xib:48: note: View is clipping its content
/* com.apple.ibtool.document.warnings */
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/Breakpad.xib:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited.
=== BUILD TARGET crash_report_sender OF PROJECT Breakpad WITH CONFIGURATION Release ===
warning: invalid character '_' in Bundle Identifier at column 18. This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters.
=== BUILD TARGET crash_report_sender OF PROJECT Breakpad WITH CONFIGURATION Release ===
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:245:29: warning: 
      'NSAlertAlternateReturn' is deprecated: first deprecated in macOS 10.10 -
      Use NSAlertFirstButtonReturn, etc instead [-Wdeprecated-declarations]
  NSInteger buttonPressed = NSAlertAlternateReturn;
                            ^
In file included from /Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:30:
In file included from ../../client/mac/sender/crash_report_sender.h:35:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:39:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSFontPanel.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPanel.h:72:5: note: 
      'NSAlertAlternateReturn' has been explicitly marked deprecated here
    NSAlertAlternateReturn NS_ENUM_DEPRECATED_MAC(10_0, 10_10, "Use NSAl...
    ^
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:248:33: warning: 
      'loadNibNamed:owner:' is deprecated: first deprecated in macOS 10.8
      [-Wdeprecated-declarations]
    BOOL didLoadNib = [NSBundle loadNibNamed:@"Breakpad" owner:self];
                                ^
In file included from /Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:30:
In file included from ../../client/mac/sender/crash_report_sender.h:35:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:91:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSNibLoading.h:31:1: note: 
      'loadNibNamed:owner:' has been explicitly marked deprecated here
+ (BOOL)loadNibNamed:(null_unspecified NSString *)nibName owner:(null_un...
^
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:269:9: warning: 
      'NSGetAlertPanel' is deprecated: first deprecated in macOS 10.10 - Use
      NSAlert instead [-Wdeprecated-declarations]
        NSGetAlertPanel([self shortDialogMessage],
        ^
In file included from /Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:30:
In file included from ../../client/mac/sender/crash_report_sender.h:35:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:39:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSFontPanel.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPanel.h:59:18: note: 
      'NSGetAlertPanel' has been explicitly marked deprecated here
APPKIT_EXTERN id NSGetAlertPanel(NSString *title, NSString *msgFormat, N...
                 ^
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:280:5: warning: 
      'NSReleaseAlertPanel' is deprecated: first deprecated in macOS 10.10 - Use
      NSAlert instead [-Wdeprecated-declarations]
    NSReleaseAlertPanel(alert);
    ^
In file included from /Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:30:
In file included from ../../client/mac/sender/crash_report_sender.h:35:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:39:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSFontPanel.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPanel.h:62:20: note: 
      'NSReleaseAlertPanel' has been explicitly marked deprecated here
APPKIT_EXTERN void NSReleaseAlertPanel(id panel) NS_DEPRECATED_MAC(10_0...
                   ^
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:282:27: warning: 
      'NSAlertDefaultReturn' is deprecated: first deprecated in macOS 10.10 -
      Use NSAlertFirstButtonReturn, etc instead [-Wdeprecated-declarations]
  return buttonPressed == NSAlertDefaultReturn;
                          ^
In file included from /Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:30:
In file included from ../../client/mac/sender/crash_report_sender.h:35:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:39:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSFontPanel.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPanel.h:71:5: note: 
      'NSAlertDefaultReturn' has been explicitly marked deprecated here
    NSAlertDefaultReturn NS_ENUM_DEPRECATED_MAC(10_0, 10_10, "Use NSAler...
    ^
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:385:28: warning: 
      'NSAlertDefaultReturn' is deprecated: first deprecated in macOS 10.10 -
      Use NSAlertFirstButtonReturn, etc instead [-Wdeprecated-declarations]
  [NSApp stopModalWithCode:NSAlertDefaultReturn];
                           ^
In file included from /Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:30:
In file included from ../../client/mac/sender/crash_report_sender.h:35:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:39:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSFontPanel.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPanel.h:71:5: note: 
      'NSAlertDefaultReturn' has been explicitly marked deprecated here
    NSAlertDefaultReturn NS_ENUM_DEPRECATED_MAC(10_0, 10_10, "Use NSAler...
    ^
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:394:28: warning: 
      'NSAlertAlternateReturn' is deprecated: first deprecated in macOS 10.10 -
      Use NSAlertFirstButtonReturn, etc instead [-Wdeprecated-declarations]
  [NSApp stopModalWithCode:NSAlertAlternateReturn];
                           ^
In file included from /Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:30:
In file included from ../../client/mac/sender/crash_report_sender.h:35:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:39:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSFontPanel.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPanel.h:72:5: note: 
      'NSAlertAlternateReturn' has been explicitly marked deprecated here
    NSAlertAlternateReturn NS_ENUM_DEPRECATED_MAC(10_0, 10_10, "Use NSAl...
    ^
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:654:18: warning: 
      'NSDeviceIndependentModifierFlagsMask' is deprecated: first deprecated in
      macOS 10.12 [-Wdeprecated-declarations]
    modifiers &= NSDeviceIndependentModifierFlagsMask;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 NSEventModifierFlagDeviceIndependentFlagsMask
In file included from /Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:30:
In file included from ../../client/mac/sender/crash_report_sender.h:35:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSActionCell.h:8:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCell.h:11:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSText.h:8:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSView.h:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSApplication.h:10:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSResponder.h:10:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:189:35: note: 
      'NSDeviceIndependentModifierFlagsMask' has been explicitly marked
      deprecated here
static const NSEventModifierFlags NSDeviceIndependentModifierFlagsMas...
                                  ^
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:655:22: warning: 
      'NSCommandKeyMask' is deprecated: first deprecated in macOS 10.12
      [-Wdeprecated-declarations]
    if (modifiers == NSCommandKeyMask) {
                     ^~~~~~~~~~~~~~~~
                     NSEventModifierFlagCommand
In file included from /Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/crash_report_sender.m:30:
In file included from ../../client/mac/sender/crash_report_sender.h:35:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSActionCell.h:8:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCell.h:11:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSText.h:8:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSView.h:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSApplication.h:10:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSResponder.h:10:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:185:35: note: 
      'NSCommandKeyMask' has been explicitly marked deprecated here
static const NSEventModifierFlags NSCommandKeyMask            NS_DEPRECA...
                                  ^
9 warnings generated.
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/Framework/OnDemandServer.mm:92:8: warning: 
      'bootstrap_subset' is deprecated: first deprecated in macOS 10.10
      [-Wdeprecated-declarations]
  kr = bootstrap_subset(bootstrap_port, self_task, &bootstrap_subset_port);
       ^
In file included from /Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/Framework/OnDemandServer.mm:30:
In file included from /Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/Framework/OnDemandServer.h:31:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/servers/bootstrap.h:61:1: note: 
      'bootstrap_subset' has been explicitly marked deprecated here
bootstrap_subset(mach_port_t bp, mach_port_t requestor_port,
^
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/Framework/OnDemandServer.mm:114:8: warning: 
      'bootstrap_create_server' is deprecated: first deprecated in macOS 10.10
      [-Wdeprecated-declarations]
  kr = bootstrap_create_server(bootstrap_subset_port,
       ^
In file included from /Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/Framework/OnDemandServer.mm:30:
In file included from /Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/Framework/OnDemandServer.h:31:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/servers/bootstrap.h:55:1: note: 
      'bootstrap_create_server' has been explicitly marked deprecated here
bootstrap_create_server(mach_port_t bp, cmd_t server_cmd, uid_t server_uid,
^
2 warnings generated.
=== BUILD TARGET breakpadUtilities OF PROJECT Breakpad WITH CONFIGURATION Release ===
warning: no rule to process file '/Users/una/item/rdm/3rdparty/gbreakpad/src/common/mac/arch_utilities.h' of type sourcecode.c.h for architecture x86_64
=== BUILD TARGET crash_report_sender OF PROJECT Breakpad WITH CONFIGURATION Release ===
/* com.apple.ibtool.document.notices */
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/Breakpad.xib:48: note: View is clipping its content
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/Breakpad.xib:66: note: View is clipping its content
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/Breakpad.xib:116: note: View is clipping its content
/* com.apple.ibtool.document.warnings */
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/Breakpad.xib:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited.
=== BUILD TARGET crash_report_sender OF PROJECT Breakpad WITH CONFIGURATION Release ===
warning: invalid character '_' in Bundle Identifier at column 18. This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters.
=== BUILD TARGET breakpadUtilities OF PROJECT Breakpad WITH CONFIGURATION Release ===
warning: no rule to process file '/Users/una/item/rdm/3rdparty/gbreakpad/src/common/mac/arch_utilities.h' of type sourcecode.c.h for architecture x86_64
=== BUILD TARGET crash_report_sender OF PROJECT Breakpad WITH CONFIGURATION Release ===
/* com.apple.ibtool.document.notices */
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/Breakpad.xib:48: note: View is clipping its content
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/Breakpad.xib:66: note: View is clipping its content
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/Breakpad.xib:116: note: View is clipping its content
/* com.apple.ibtool.document.warnings */
/Users/una/item/rdm/3rdparty/gbreakpad/src/client/mac/sender/Breakpad.xib:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited.
=== BUILD TARGET crash_report_sender OF PROJECT Breakpad WITH CONFIGURATION Release ===
warning: invalid character '_' in Bundle Identifier at column 18. This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters.
Error: libssh2 1.8.0 already installed
Warning: libssh2 1.8.0 is already installed and up-to-date
To reinstall 1.8.0, run `brew reinstall libssh2`

**Comment by uglide** [comment] 2018-05-09 09:14
Looks like duplicate of #4113

**Closed as completed by uglide** 2018-05-09 09:14 UTC
