### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by KaranChatrani** [redis/RedisDesktopManager#4069] opened 2018-03-29 06:12 UTC
RDM Version: 0.9.1.771
Environment (OS name and version): Windows 10 Pro
Redis Server Version: 0.9.1.771

Steps to reproduce:

1.Apply Filter

Expected result: Cached keys should load

Actual Result: Filter is not working. even a single key is not loading.

**Comment by joemore** [comment] 2018-04-02 09:06
This is also broken for me. I cannot filter any of my keys. It does not work on any of my Redis connections and seems to be the Redis Desktop Manager itself.

RDM Version 0.9.1.37
Environment macOS High Sierra V10.13.3

**Comment by uglide** [comment] 2018-04-04 15:26
Duplicate of #4060

**Closed as completed by uglide** 2018-04-04 15:26 UTC
Labels: duplicate
