### ISSUE TITLE
Redis Cluster Gui Crashed

### ISSUE THREAD

**Issue by byazrail** [redis/RedisDesktopManager#4168] opened 2018-07-17 11:29 UTC
RDM Version: 0.9.3.39
Environment (OS name and version): Mac OS
Redis Server Version: 4.0.10

Steps to reproduce:
Redis Cluster Connection ok.
Db List ok.
Db data exit crash gui.
Expected result: 

Actual Result: 
<img width="1478" alt="screen shot 2018-07-17 at 14 28 25" src="https://user-images.githubusercontent.com/5870455/42814718-c569c8d0-89cd-11e8-8732-0f8454db0578.png">
<img width="390" alt="screen shot 2018-07-17 at 14 28 55" src="https://user-images.githubusercontent.com/5870455/42814719-c591894c-89cd-11e8-9a5a-11b671f7f5cb.png">

**Comment by uglide** [comment] 2018-09-14 10:28
Cannot reproduce on 0.9.6

**Comment by byazrail** [comment] 2018-09-14 12:16
Version : 0.9.6.58 problem continue;
SSH Tunnel connection db select after crashed.
<img width="680" alt="screen shot 2018-09-14 at 15 14 04" src="https://user-images.githubusercontent.com/5870455/45549581-fb5e4380-b830-11e8-8f2f-b6f17822c408.png">
<img width="1108" alt="screen shot 2018-09-14 at 15 14 22" src="https://user-images.githubusercontent.com/5870455/45549582-fbf6da00-b830-11e8-8276-f097a3fc1d2d.png">
<img width="782" alt="screen shot 2018-09-14 at 15 14 32" src="https://user-images.githubusercontent.com/5870455/45549583-fbf6da00-b830-11e8-861d-cd54e4b8b3f4.png">

**Comment by uglide** [comment] 2018-09-14 13:53
Can reproduce it now. Thanks!

**Comment by uglide** [comment] 2018-09-20 10:37
Fixed and will be released in 0.9.7

**Closed as completed by uglide** 2018-09-20 10:37 UTC
Labels: bug

**Comment by byazrail** [comment] 2018-09-20 12:12
@uglide Thanks ^_^

**Comment by byazrail** [comment] 2018-09-24 14:51
<img width="1483" alt="screen shot 2018-09-24 at 17 50 18" src="https://user-images.githubusercontent.com/5870455/45959394-74744c80-c022-11e8-8aca-986cabce3424.png">

Thanks bug fixed. ^_^

**Comment by uglide** [comment] 2018-09-24 15:01
You are welcome! Thanks for the bug report!
