### ISSUE TITLE
The interface cannot be displayed properly

### ISSUE THREAD

**Issue by jelipo** [redis/RedisDesktopManager#3840] opened 2017-05-20 07:35 UTC
RDM Version: 0.80 - 0.90<br>
Environment (OS name and version): Windows10 1703<br>
Redis Server Version: none<br>

Steps to reproduce:

[screenshot](http://i1.piimg.com/1949/5ccbdba00a2a0bd4.png)

I installed the 0.88 version of RDM.But interface cannot be displayed properly.
Then I installed the 0.90 version of RDM, and the problem remains.
I tried installing many versions.And I found that the RDM version of the 0.76 version was able to display properly.
I thought it was a system problem.Then I reinstall the system.In the beginning, RDM was normal.
But after all the drivers are installed, the RDM doesn't display properly again.

The interface looks stretched.The position of the mouse pointer and button will also be misplaced.

My notebook is GIGABYTE aero15.

**Comment by uglide** [comment] 2017-09-14 09:14
Duplicate of #3863

**Closed as completed by uglide** 2017-09-14 09:14 UTC
Labels: duplicate
