### ISSUE TITLE
Is not possible create a new connection without password.

### ISSUE THREAD

**Issue by bcfurtado** [redis/RedisDesktopManager#3308] opened 2015-01-16 16:36 UTC
Version: 0.7.6.8
Environment: Ubuntu 14.10
Redis Server Version: 2.8.5

Steps to reproduce:
1.Click on RedisDesktopManager.ink
2.Click on Add Connection button  
3.Fill all connections settings correctly.
4.Enable SSH Tunel, but dont enable password option. (This is necessary when we need make login without password only using ssh keys )

Expected result: New connection added on list of connections.

Actual Result: Invalid settings detected.

**Comment by wkoot** [comment] 2015-02-19 10:09
Confirmed, same behaviour on Windows (0.7.6.15).

I'm trying to use a SSH key to connect, but cannot do this without a working password.
So I cannot tunnel through SSH if I do not have a user that only supports key-auth.
Also, it seems that the unticking of password field is not stored anyway.
When you click Edit afterwards, it's always unticked.

**Comment by uglide** [comment] 2015-03-30 11:29
Duplicate of #1874

**Closed as completed by uglide** 2015-03-30 11:29 UTC
Labels: bug, duplicate
