### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by ellwoods** [redis/RedisDesktopManager#4130] opened 2018-05-24 07:38 UTC
RDM Version: 0.9.3.817<br>
Environment (OS name and version): Win 10 Pro 1709 build 16299.192<br>
Redis Server Version: 4.0.6<br>

Steps to reproduce:

1. Open RDM and connect to an instance. Open a db and drill down to some data

Expected result:  Ability to scroll using scroll bar on  left hand side

Actual Result: When I Try to access the scroll bar on the left the cursor changes to the divider icon which lets me make the region wider or narrower. Unable to scroll using the scroll bar. This makes it awkward and very time consuming to move around when I only have a few thousand records

**Comment by uglide** [comment] 2018-10-08 09:04
@ellwoods I cannot reproduce it on my Windows setup (4k screen + 200% scaling + 1803)

Could you provide more details on your screen resolution and scaling factor?
Probably something was changed in windows internals since 1709

**Comment by uglide** [comment] 2018-10-09 07:18
I'm closing it for now. If you still see this issue on 1803 or 1809 please reopen it with screenshots and details.

**Closed as completed by uglide** 2018-10-09 07:18 UTC
Labels: bug, windows, Can't reproduce, waiting for feedback
