### ISSUE TITLE
Namespace separator not saved.

### ISSUE THREAD

**Issue by GrzegorzDrozd** [redis/RedisDesktopManager#3442] opened 2015-08-14 14:24 UTC
Hi.

In 0.8.0.3840 on Windows, in server settings, namespace separator is not saved between program runs.

Have a nice day.

**Comment by uglide** [comment] 2015-08-16 10:55
Hello @GrzegorzDrozd 

I cannot reproduce this problem, Could you provide more details? Which NS separator do you use? Also could you provide steps to reproduce?

**Comment by SirDice** [comment] 2015-08-18 16:43
I have the same issue. Edit Connection -> Advanced Settings -> Namespace separator. I've set it to : (colon) but have to set it each time I start the application. 

Running 0.8.0.3840 on Windows 7 Professional (64 bit).

**Comment by GrzegorzDrozd** [comment] 2015-08-18 19:28
Sorry for the delay. Yes, I did the same: edit, advanced. Same separator. 

My instalation is an update but I don't remember previous version.

**Comment by filipealonso** [comment] 2015-08-19 08:32
+1 (Windows 10 Pro, 64bit)

**Comment by andrebires** [comment] 2015-08-19 12:49
Same issue here, version 0.8.0.3840, Windows 10 Pro 64 bit.

**Comment by uglide** [comment] 2015-08-20 10:08
@GrzegorzDrozd @SirDice @filipealonso @andrebires 
Temprorary work-around: remove connections.xml file from `C:\Users\%YOUR_USER%\.rdm\connections.xml`

**Comment by uglide** [comment] 2015-08-21 08:48
Fix pushed to master and will be released with 0.8.0-Release

**Closed as completed by uglide** 2015-08-21 08:48 UTC
Labels: bug, major
