### ISSUE TITLE
selecting more than a single key

### ISSUE THREAD

**Issue by ongley** [redis/RedisDesktopManager#2724] opened 2014-10-15 13:43 UTC
First of all, I'd want to mention the amazing speed of RDM comparing to phpredisadmin.
But there is a bug, that cosumes a lot of time.
When selecting a single key everything's ok, but when clicking on another key RDM shows empty window and that behaviour preserves until I reopen RDM.

![screenshot_1](https://cloud.githubusercontent.com/assets/5292842/4646307/22aa7c0a-5472-11e4-8c2a-ed9214d1520e.png)

I got a windows client v.0.7.6, connect to redis via ssh tunnel.
Thanks for an answer.

**Comment by uglide** [comment] 2014-10-16 12:31
Thank you for feedback, probably this is duplicate of #2208. I will fix it in 0.8.0

**Closed as completed by uglide** 2014-10-16 12:31 UTC
