### ISSUE TITLE
did not show string

### ISSUE THREAD

**Issue by wangdyqxx** [redis/RedisDesktopManager#3937] opened 2017-12-08 09:14 UTC
Can you find out what the problem is?

![1512724420 1](https://user-images.githubusercontent.com/26316940/33758869-1d318ecc-dc3b-11e7-9fbf-96361ac79218.jpg)

**Comment by uglide** [comment] 2017-12-08 10:38
Duplicate of #3938

**Closed as completed by uglide** 2017-12-08 10:38 UTC
