### ISSUE TITLE
Bad "View as" pre-selection

### ISSUE THREAD

**Issue by PauloASilva** [redis/RedisDesktopManager#3582] opened 2016-02-04 13:13 UTC
**Version:** 0.8.3-120
**Environment:** Linux LAPTOP 3.13.0-76-generic #120-Ubuntu SMP Mon Jan 18 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
**Redis Server Version:** 2.8.12

**Steps to reproduce:**
1. SET mykey [307522 characters long string]
2. Click on RDM to get `mykey`

**Expected result:**
- `Value` should show the long string
- `View as` 
  - no pre-selection should be done or 
  - the default value (if any) should be taken or
  - infer `View as` value from Redis `TYPE mykey` command response

Actual Result: 
- `Value` shows `null`
- `View as` was (WRONGLY) pre-selected with `PHP Serializer (READ ONLY)`

Transaction log for mykey is below

```
2016-02-04 12:50:15 : Click on tree item: 0
2016-02-04 12:50:15 : Connection: localhost > [runCommand] type mykey
2016-02-04 12:50:15 : Connection: localhost > [runCommand] type mykey -> response received : +string
2016-02-04 12:50:15 : Connection: localhost > [runCommand] ttl mykey
2016-02-04 12:50:15 : Connection: localhost > [runCommand] ttl mykey -> response received : 
2016-02-04 12:50:15 : Connection: localhost > [runCommand] GET mykey
2016-02-04 12:50:16 : Connection: localhost > [runCommand] GET mykey -> response received : Bulk
```

**Comment by uglide** [comment] 2016-02-06 13:40
Looks like first char of your string is 'N'. And this issue is duplicate of #3552

**Closed as completed by uglide** 2016-02-06 13:40 UTC
Labels: duplicate
