### ISSUE TITLE
distortion code, wo can't read

### ISSUE THREAD

**Issue by binlaniua** [redis/RedisDesktopManager#678] opened 2014-01-20 03:39 UTC
![image](https://f.cloud.github.com/assets/5960462/1951562/472af09e-8184-11e3-843a-468a470edb17.png)

**Comment by uglide** [comment] 2014-02-11 12:24
Can you provide sample string for testing?

**Comment by candyman888** [comment] 2014-04-09 22:30
I have the same problem all keys display in this format.  Clicking on any entry gives me a message "Can not load key value. Key was removed or redis-server went away."  I'm on Windows XP.  Haven't been able to get past this to use the software.

**Comment by uglide** [comment] 2014-10-16 12:25
Duplicate of #1718

**Closed as completed by uglide** 2014-10-16 12:25 UTC
Labels: bug, Can't reproduce
