### ISSUE TITLE
RedisDesktopManager will lose its response when i just press test connection

### ISSUE THREAD

**Issue by ResolveWang** [redis/RedisDesktopManager#3811] opened 2017-03-07 11:05 UTC
RDM Version: redis-desktop-manager-0.9.0.41.dmg <br>
Environment (OS name and version):  Darwin Kernel Version 16.4.0:root:xnu3789.41.3~3/RELEASE_X86_64 x86_64<br>

When I press test connection,, it will lose reponse.I have to use `kill -9 pid
`to kill it

**Comment by uglide** [comment] 2017-03-29 08:40
Duplicate of https://github.com/uglide/RedisDesktopManager/issues/3735

**Closed as completed by uglide** 2017-03-29 08:40 UTC
Labels: duplicate
