### ISSUE TITLE
Cannot connect SSH with passphrase

### ISSUE THREAD

**Issue by ducminhgd** [redis/RedisDesktopManager#3571] opened 2016-01-25 05:06 UTC
Shortly: I'm using SSH tunnel with a private key and passphrase, I tried to input passphrase in password field, but it didn't work.

Details: I have two servers, Web and Redis, Redis server allows only Web server connect via 6379 port. I have to SSH to Web server and connect to Redis Server. It works on command line, but doesn't work in Redis Desktop Manager
##

**Comment by uglide** [comment] 2016-01-25 07:11
Hello @ducminhgd 
Thanks for the feedback, I will ty to reproduce this issue

**Comment by uglide** [comment] 2016-01-25 09:51
@ducminhgd btw Do you use key in PEM format?

**Comment by ducminhgd** [comment] 2016-01-25 10:03
@uglide Yes.
And when will new version be released? I'm looking forward to its release day.

**Comment by uglide** [comment] 2016-01-25 10:07
@ducminhgd I expect to release the first beta of 0.9.0 in the middle of February. Final release dates you can find on [milestones page](https://github.com/uglide/RedisDesktopManager/milestones)

**Comment by uglide** [comment] 2016-01-25 10:08
@ducminhgd One more question, Which OS & Version Do you use?

**Comment by ducminhgd** [comment] 2016-01-25 10:11
@uglide I'm using Windows 10, RDM 0.8.3. Windows 7 has the same issue too.

**Comment by uglide** [comment] 2016-01-25 10:13
@ducminhgd ok, thanks

**Comment by laurencei** [comment] 2017-08-25 00:23
I have this same issue. Is there any ability to use a passphrase for the key?

**Comment by uglide** [comment] 2018-05-09 09:12
Cannot reproduce on current 0.9 branch (0.9.3 release). Probably duplicate of #4047 or already fixed

**Closed as completed by uglide** 2018-05-09 09:12 UTC
Labels: bug
