### ISSUE TITLE
Windows 10- GUI cannot display in a high resolution: 1920x1080.

### ISSUE THREAD

**Issue by letrthang** [redis/RedisDesktopManager#4086] opened 2018-04-06 14:59 UTC
RDM Version: 0.9.1.771<br>
Environment (OS name and version): Windows 10 64 bit<br>
Redis Server Version: any <br>

GUI cannot display in a high resolution: 1920x1080.

step1: just click on **Setting** button to see the result.

**Comment by uglide** [comment] 2018-04-06 16:07
Please provide screenshot for described problem

**Comment by letrthang** [comment] 2018-04-06 16:12
It is here. see at the bottom picture.
[https://ibb.co/dt3u7H](https://ibb.co/dt3u7H)

**Comment by lovinhence** [comment] 2018-04-14 08:56
Same problem on my pc too.

**Comment by vincenzo-antolini-os** [comment] 2018-04-21 05:44
Same here

**Comment by uglide** [comment] 2018-04-30 10:58
Duplicate of #4089

**Closed as completed by uglide** 2018-04-30 10:58 UTC
