### ISSUE TITLE
JSON view shows wrong values for long numbers

### ISSUE THREAD

**Issue by alexandar** [redis/RedisDesktopManager#3650] opened 2016-07-15 13:47 UTC
RDM Version: 0.8.6.270 <br>
Environment (OS name and version): Windows [Version 10.0.10586] <br>
Redis Server Version: 3.0.501<br>

Steps to reproduce:
1. Add new key with value `{
   "Instance": 732189744448016455
   }` 
2. Click on the added key

Expected result: `{
    "Instance": 732189744448016455
}` 

Actual Result: `{
    "Instance": 732189744448016400
}`

**Comment by uglide** [comment] 2016-07-15 14:07
Duplicate of #3641

**Closed as completed by uglide** 2016-07-15 14:07 UTC
Labels: duplicate
