### ISSUE TITLE
bug with hset 

### ISSUE THREAD

**Issue by Fandel-Chuang** [redis/RedisDesktopManager#4070] opened 2018-03-29 14:45 UTC
RDM Version: 0.9.1.771<br>
Environment (OS name and version):win10 <br>
Redis Server Version: x64-3.2.100<br>

Steps to reproduce:

1. ...Select a hash key

2. ... change value

3. ... click save button

Expected result: 
value changed
Actual Result: 
![1](https://user-images.githubusercontent.com/16217224/38095313-c6c7840a-33a2-11e8-8e85-eaa2e4ce3b11.png)
![2](https://user-images.githubusercontent.com/16217224/38095314-c7140faa-33a2-11e8-90ae-e5dcf404eeb1.png)

value don't change

**Comment by uglide** [comment] 2018-04-04 14:04
Duplicate of #4056

**Closed as completed by uglide** 2018-04-04 14:04 UTC
Labels: duplicate
