### ISSUE TITLE
RDM's connect window can't zoom out 

### ISSUE THREAD

**Issue by SealinGp** [redis/RedisDesktopManager#4089] opened 2018-04-10 01:30 UTC
RDM Version: <br> 0.9.1.771
Environment (OS name and version): <br> Windows 10 education
Redis Server Version: <br>3.0.503

Steps to reproduce:

my screen size is small , when i run the RDM, click the 'connect' button,  I can't click the 'OK' button because the connect window's heigh overflow my screen, when i try to zoom out  it ,it didn't work

Expected result: 

Actual Result:

**Comment by uglide** [comment] 2018-04-10 16:04
Please specify your screen resolution

**Comment by SealinGp** [comment] 2018-04-11 09:24
@uglide  my labtop's screen resolution is 1920*1080, my screen size is 14 inches

**Comment by uglide** [comment] 2018-04-11 12:10
@SealinGp What is your scaling factor? 150%?

**Comment by SealinGp** [comment] 2018-04-12 02:04
@uglide yep,150%,It is recommed,should i  adjust to 125%?,but there is still existing problem when i change it to 125%, I will send you  the relevent screen shot  by email

**Comment by SealinGp** [comment] 2018-04-12 02:05
Hi
here is the  screent shot
Thanks
Sea


SealinGp@163.com
 
From: Igor Malinovskiy
Date: 2018-04-11 20:10
To: uglide/RedisDesktopManager
CC: SealinGp; Mention
Subject: Re: [uglide/RedisDesktopManager] RDM's connect window can't zoom out (#4089)
@SealinGp What is your scaling factor? 150%?

**Comment by uglide** [comment] 2018-08-02 10:02
Duplicate of #4123

**Closed as completed by uglide** 2018-08-02 10:02 UTC
