### ISSUE TITLE
cluster mode get same keys

### ISSUE THREAD

**Issue by foreverhot1019** [redis/RedisDesktopManager#4094] opened 2018-04-16 00:43 UTC
RDM Version: 0.9.2.806<br>
Environment (OS name and version): win10 1709<br>
Redis Server Version: 3.2.100<br>

Steps to reproduce:

1. ...

2. ...

3. ...

Expected result: 
get  4 same key (3 cluster node)

Actual Result: 
get  1 key

**Comment by ImRealDR** [comment] 2018-04-17 09:38
i have same problem

**Comment by uglide** [comment] 2018-04-30 10:55
Duplicate of #4058

**Closed as completed by uglide** 2018-04-30 10:55 UTC
