### ISSUE TITLE
SSH tunnelled connection doesn't work (no keys listed)

### ISSUE THREAD

**Issue by iafan** [redis/RedisDesktopManager#1015] opened 2014-02-13 19:29 UTC
I created a new connection via SSH tunnel. The app connects to a remote server, then lists all the databases as empty ones. Clicking on each database will display some ghost 'OK' key (this key doesn't exist) and won't show any real keys — see the image attached. If I open the console then type in the `info` command, I do see a proper response from the redis server, which tells me, among other preferences, the proper number of keys: `db0:keys=215,expires=0`

Redis server version is 2.4.15, running under Debian. Will be happy to provide any additional information here or over Skype.

![screenclip 4](https://f.cloud.github.com/assets/1728158/2163836/a1ca4202-94e4-11e3-930f-f27cab1f91ce.png)

**Comment by uglide** [comment] 2014-02-18 12:49
I fixed issue with counter, but I can't reproduce issue with ghost key "OK". Please join to public skype chat http://tinyurl.com/o44bk5g and describe details.

Many thanks!

**Comment by uglide** [comment] 2014-02-19 10:43
Fixed in 0.7.6

**Closed as completed by uglide** 2014-02-19 10:43 UTC
Labels: bug
