### ISSUE TITLE
Add read-only value view formatter for binary strings

### ISSUE THREAD

**Issue by SergeC** [redis/RedisDesktopManager#3423] opened 2015-08-08 19:25 UTC
Plain text view doesn't work on OS X 10.9 if string contains zero bytes. Hex view works only for me. On screenshot you can see that I have a content (look at Redis Browser) while RDM shows empty field.
![screen shot 2015-08-08 at 22 21 30](https://cloud.githubusercontent.com/assets/1062847/9151862/599dbcce-3e1c-11e5-8445-f83b4d336fb7.png)

**Comment by uglide** [comment] 2015-08-09 13:52
Thanks for the feedback! Simple workaround for this bug - is reloading this key (just click again on the key). This issue will be fixed in 0.8.0-RC2

**Comment by SergeC** [comment] 2015-08-09 14:32
Sorry, didn't work for me. I clicked 3 times on key in left tree. See log window at RDM. The value window is still empty.

![screen shot 2015-08-09 at 17 29 28](https://cloud.githubusercontent.com/assets/1062847/9155301/806fad4e-3ebc-11e5-8536-b3130b937dc8.png)

**Comment by SergeC** [comment] 2015-08-13 19:45
Reopening. Doesn't work build 2539 on OS X 10.9.5. Problem is the same.

**Comment by uglide** [comment] 2015-08-14 05:58
@SergeC Are you shoure that you use correct version of RDM? I cannot reproduce this problem on RC2 and RC3

**Comment by SergeC** [comment] 2015-08-14 21:15
Yes, I'm sure. Last version in use. Emailed you regarding this issue.

**Comment by SergeC** [comment] 2015-08-20 18:24
Is any update on my issue and email I've sent?

**Comment by uglide** [comment] 2015-08-21 15:11
Related to #3310

**Comment by SergeC** [comment] 2015-09-30 07:40
On Ubuntu works perfect. But on Mac problem still exists.

**Comment by uglide** [comment] 2015-10-12 16:24
Fixed by 4a5b9a9f45307e82b57f38e041a6d739cdbac4cb in 0.8.0-RC5 (will be released soon)

**Closed as completed by uglide** 2015-10-12 16:24 UTC
Labels: enhancement
