### ISSUE TITLE
If key starts with "O" the view switches to PHP.

### ISSUE THREAD

**Issue by yene** [redis/RedisDesktopManager#3591] opened 2016-02-18 14:33 UTC
On OS X 10.11.3

Steps
- press Add row
- enter as key: "Otest"
- press ok
- click on the new entry

Problem
- View as is set to PHP not Plain Text

**Comment by uglide** [comment] 2016-02-19 07:02
Duplicate of #3552

**Closed as completed by uglide** 2016-02-19 07:02 UTC
Labels: duplicate
