### ISSUE TITLE
0.9.0 Can't connect to Azure Redis caches

### ISSUE THREAD

**Issue by tcgielow** [redis/RedisDesktopManager#3996] opened 2018-02-07 23:03 UTC
RDM Version: 0.9.0.684
Environment (OS name and version): Windows 10 build 17083
Redis Server Version: Azure Redis

Steps to reproduce:

1. Enter the settings just as they worked on 0.8.8.834 version and it simply cannot connect. 

2. Downgrade to 0.8.8.834 and works perfectly

3. ...

Expected result: 

Actual Result:

**Comment by uglide** [comment] 2018-02-08 09:23
Duplicate of #3980

**Closed as completed by uglide** 2018-02-08 09:23 UTC
