### ISSUE TITLE
App crash when attempting to receive very large cache item

### ISSUE THREAD

**Issue by tylerohlsen** [redis/RedisDesktopManager#3608] opened 2016-04-14 17:08 UTC
RDM Version: 0.8.3.3850
Environment (OS name and version): Win10 Insider Preview
Redis Server Version: Azure Redis (exact version unknown)

Steps to reproduce:
1. Connect to a Redis server 
2. Attempt to receive a cache item that is very large in size

Expected result: 
- The cached item will be received and displayed in UI

Actual Result: 
- Application crashes

**Comment by tylerohlsen** [comment] 2016-04-14 17:12
I've tried setting the Connection Timeout and Execution Timeout settings on the connection properties to a large number, but that does not seem to help as it still crashes after the same time period.  

I believe we are missing a way to set the Redis [SyncTimeout ](https://azure.microsoft.com/en-us/blog/investigating-timeout-exceptions-in-stackexchange-redis-for-azure-redis-cache/) property.

**Comment by uglide** [comment] 2016-04-25 10:28
Duplicate of #3599

**Closed as completed by uglide** 2016-04-25 10:28 UTC
Labels: duplicate
