### ISSUE TITLE
About the GUI in Windows 10

### ISSUE THREAD

**Issue by StartMoney** [redis/RedisDesktopManager#3931] opened 2017-11-06 10:26 UTC
RDM Version: <br>
![_20171106181329](https://user-images.githubusercontent.com/13027030/32436208-4193ea7a-c31e-11e7-99e7-171a60c7dbd4.png)

Environment (OS name and version): windows 10<br>
Redis Server Version: <br>

it seems there are some wrong whith the GUI of the tool.
and when i click one server item in the left list, it was focus the one above it :( 

![_20171106182505](https://user-images.githubusercontent.com/13027030/32436690-d64e85ac-c31f-11e7-8147-32c01f4ac84f.png)

i tried from 8.0 beta to 9.0 beta5 ,  no one version is wroked well.

**Comment by StartMoney** [comment] 2017-11-06 10:31
my notebok : dell xps 15 ,   1920*1080 , 100% scale

**Comment by uglide** [comment] 2017-11-06 14:10
Duplicate of  #3876

**Closed as completed by uglide** 2017-11-06 14:10 UTC
Labels: duplicate
