### ISSUE TITLE
Connection: SSH Connection error: Authentication Error

### ISSUE THREAD

**Issue by qlwz** [redis/RedisDesktopManager#3872] opened 2017-07-26 03:10 UTC
RDM Version: all
Environment (OS name and version): win10
Redis Server Version: 3.2

Steps to reproduce:

 use SSH tunnel

 set private key and password 

Expected result: 
Connection OK

Actual Result: 

Connection: SSH Connection error: Authentication Error

**Comment by SvenAbels** [comment] 2017-08-13 22:30
same problem here

**Comment by uglide** [comment] 2017-08-25 08:41
Duplicate of #3571

**Closed as completed by uglide** 2017-08-25 08:41 UTC
Labels: duplicate
