### ISSUE TITLE
No DB keys amount displayed anymore

### ISSUE THREAD

**Issue by piotrkochan** [redis/RedisDesktopManager#3435] opened 2015-08-12 06:00 UTC
Hi, in newest RDM version there is no information about keys amount in databases.
Probably this is because of performance but I think that there should be some kind of setting to turn this on

**Comment by uglide** [comment] 2015-08-12 12:18
Duplicate of #3429

@piotrkochan FYI 0.8.0-RC2 will be released today ;)

**Closed as completed by uglide** 2015-08-12 12:18 UTC

**Comment by piotrkochan** [comment] 2015-08-12 13:21
@uglide nice, thanks for notification :)
