### ISSUE TITLE
Changing page in Set not working

### ISSUE THREAD

**Issue by Sorcy** [redis/RedisDesktopManager#3514] opened 2015-10-23 09:41 UTC
When selecting a set and then changing from page 1 to any other page (either by the arrow keys, or by directly selecting a page) I get the loading animation and it keeps being displayed and the new page not being loaded. This continues until I select another key.

**Comment by uglide** [comment] 2015-10-23 12:32
Duplicate of #3503. This bug was fixed in 0.8.1. Please download latest release. Thanks!

**Closed as completed by uglide** 2015-10-23 12:32 UTC
Labels: duplicate
