### ISSUE TITLE
Using live update immediately before and after a DB flush results in multiple DB entries showing up

### ISSUE THREAD

**Issue by barrychapman** [redis/RedisDesktopManager#4126] opened 2018-05-17 03:44 UTC
RDM Version: 0.9.3.817<br>
Environment (OS name and version): CentOS 7.4<br>
Redis Server Version: Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=8e246a05989e6d22
<br>

Steps to reproduce:

1. Connect to Server

2. Enable Live Update

3. Load some stuff from the server to populate the  records

4. Flush the db

5. Enable Live Update again

6. Reload stuff from the site to force populating Redis

7. Observe the duplicate keys showing in redis

Expected result: Only one key should show up

Actual Result: Multiple keys of the same show up
![image](https://user-images.githubusercontent.com/152958/40155636-d00e7dbc-5962-11e8-838d-11be46b8526a.png)
![image](https://user-images.githubusercontent.com/152958/40155639-e01359da-5962-11e8-82b6-114bf843570f.png)
![image](https://user-images.githubusercontent.com/152958/40155649-ea7df7b8-5962-11e8-8488-c7971f3734cd.png)

**Comment by uglide** [comment] 2018-05-30 13:48
Duplicate of #3995

**Closed as completed by uglide** 2018-05-30 13:48 UTC
