### ISSUE TITLE
SSH tunnel not working on Ubuntu 15.10

### ISSUE THREAD

**Issue by atrauzzi** [redis/RedisDesktopManager#3597] opened 2016-02-28 06:11 UTC
![image](https://cloud.githubusercontent.com/assets/115199/13377772/6e3a1e06-ddaf-11e5-9f64-d60be9541a23.png)

Having troubles getting the tunnel going: 

![image](https://cloud.githubusercontent.com/assets/115199/13377785/c35d4e80-ddaf-11e5-93f7-521233568d54.png)

I'm able to connect to other services on the host using a tunnel (DataGrip and PostgreSQL).  I'm also able to manually SSH into the machine and telnet to the redis server.  So it's definitely accessible.

**Comment by uglide** [comment] 2016-03-10 09:08
Duplicate of #3568

**Closed as completed by uglide** 2016-03-10 09:08 UTC
Labels: duplicate
