### ISSUE TITLE
Can not select list value column when page is larger than 1

### ISSUE THREAD

**Issue by Jerry-Shaw** [redis/RedisDesktopManager#5079] opened 2021-07-09 06:09 UTC
**Describe the bug**
Value column is unselectable in list when page is not 1. Only values in page 1 can be selected.

**To Reproduce**
1. Lpush data to list more than 1 page.
2. Select next page or jump to any other page over 1.
3. Try to select value columns
4. CAN NOT select any column

**Expected behavior**
Any value can be selected and viewed below.

**Environment (please complete the following information):**
 - Windows 10 19043.1082
 - Redis-Server version 5.0.9

**Comment by uglide** [comment] 2021-07-09 12:48
Thanks for the bug report but it's duplicate of #5068 which is already fixed and will be released in 2021.6 soon

**Closed as completed by uglide** 2021-07-09 12:48 UTC
Labels: bug

**Comment by Jerry-Shaw** [comment] 2021-07-09 13:29
Haha, thanks for reply. Wait for new version.
