### ISSUE TITLE
Issues with Application rendering (Windows 10)

### ISSUE THREAD

**Issue by josefguenther** [redis/RedisDesktopManager#3876] opened 2017-08-03 19:44 UTC
RDM Version: 0.8.8.384
Environment (OS name and version): Windows 10
Redis Server Version: n/a

I have a laptop with a 4k screen. It is scaled at 225%. The application renders correctly, but attempting to click any of the items in the left or right window control does not work as expected.

Steps to reproduce:

1. Open RDM on scaled display.

2. Attempt to click links in either left or right window control. This includes connections and databases on the left, and any of the welcome screen links on the right..

Actual Result: The mouse cursor must be a bit below the actual link to hover/click. I would guess 40 pixels.

**Comment by bwarring** [comment] 2017-08-05 12:22
Same issue for me.  I am able to work around by placing cursor slightly below the actual link as mentioned by @josefguenther .  RDM is a great product and I will continue using regardless however; a solution to this issue would be awesome.  As a side note, I have had similar 4k graphic issues with other products such as Eclipse (Neon version seems to handle the best).

Comments are descriptive, but I've uploaded a couple images for a visual of how I am required to place the cursor:
![redis desktop manager 4k graphics issue](https://user-images.githubusercontent.com/4380641/28995421-83581be8-79ae-11e7-9a1f-04dbc1e8cb88.jpg)
![redis desktop manager 4k graphics issue 2](https://user-images.githubusercontent.com/4380641/28995422-8ba51300-79ae-11e7-8941-12ff273fd4d6.jpg)

**Comment by josefguenther** [comment] 2017-08-06 02:29
Great screenshots, couldn't get my mouse cursor in there.

I discovered another related issue as well. I have two displays: Primary (scaled at 225%) and Secondary (scaled at 125%). When I put the RDM application on the Secondary, lower scale display, I get the same issues described before plus two additional issues: the titlebar of the application is unusually large and the top of the window body cuts off.

See attached, and pay special attention to:
- the left database list which is cut off on the top
- The top titlebar (including icon, title and window control buttons) which is unusually large.

![image 4](https://user-images.githubusercontent.com/1220566/29000035-a95b6f74-79fa-11e7-8331-e97ec71fa2f4.jpg)

**Comment by VictorVanV** [comment] 2017-08-07 15:37
Also pop ups are oddly scaled, in this case the TTL setup window.
I've a dell XPS laptop with a 4k screen, however I don't (currently) use the laptop screen. Instead I've 3 1080p monitors attached to it. No scaling configured at all.
![image](https://user-images.githubusercontent.com/375177/29033913-e550b190-7b96-11e7-9294-689b6d74459b.png)
Windows 10 Pro

**Comment by jsheely** [comment] 2017-08-16 12:55
Anyone know how to solve this? My screens are currently not set with any scaling and it still looks like this on Windows 10 w/ Creators Update.

![image](https://user-images.githubusercontent.com/1424946/29364161-9f0bd068-8260-11e7-856e-6407ed001d0a.png)

**Comment by olaj** [comment] 2017-08-30 13:40
Same issue here :/

**Comment by ryankelley** [comment] 2017-08-30 18:30
I am also having the same issues, I don't have a workaround yet.

**Comment by jsheely** [comment] 2017-09-13 13:12
I've tried messing with the configuration settings for QT GUI but it didn't seem to have an effect. Not Sure I did it right.

http://doc.qt.io/qt-5/highdpi.html

**Comment by Xh4H** [comment] 2017-09-20 07:47
I'm having the same issue... Works fine on my main pc, but it won't in my laptop.
![image](https://user-images.githubusercontent.com/20613820/30632496-9b70f9d0-9de8-11e7-8394-3a42a5e3e1f6.png)

**Comment by uglide** [comment] 2017-09-20 11:59
@josefguenther @olaj @PurgePJ @ryankelley 

Guys, Could you check how it works on latest 0.9 build?
https://ci.appveyor.com/api/buildjobs/4n8yeo9sfn5mhsj9/artifacts/build%2Fwindows%2Finstaller%2Fredis-desktop-manager-0.9.0.612.exe

**Comment by jsheely** [comment] 2017-09-20 14:51
It still as a few issues but it's getting better. 

The most notable issue is that the list on the left looks okay and is visible now but the location where I click on them doesn't line up with the item that the event triggers on. I have to click a little below it. Same with all the buttons when looking a specific key.

![image](https://user-images.githubusercontent.com/1424946/30650679-8728bfae-9df1-11e7-861f-ced0407cf925.png)

**Comment by uglide** [comment] 2017-09-20 15:00
@jsheely still not visible toolbar...
thanks for your help, will try to setup testing env to reproduce issue

**Comment by jsheely** [comment] 2017-09-20 15:04
@uglide You look into that QT high-dpi scaling setting link I posted earlier? You may be able to implement that setting change at the app level. I tried adding it to the config file but not sure if it took effect because nothing changed.

The strange part is I have a standard 1080 laptop w/ no scaling turned on yet it still acts like it's scaling.

**Comment by uglide** [comment] 2017-09-20 15:09
@jsheely Probably you have modified scaling properties in app settings...

**Comment by josefguenther** [comment] 2017-09-20 22:53
@uglide I tried the new version you uploaded. Again I have a 4k 15.6 inch display scaled at 225%. Here are my findings:

- I have the same issues with right/bottom cut off as @jsheely 
- There is now no hover effect on the left items (databases). This presents a problem since I still have to click 40px below the actual item (the issue is not fixed) which makes it unusable as I now no longer can see which item I'm actually clicking on. It's guesswork.
- I cannot open any database as I get the following error: Cannot load keys: Scan commands not supported by redis-server. I am using a local redis server (redis_version:2.4.6). I realize that this issue is totally unrelated and if you want me to open another issue, I'll do so.

Thanks for working on this...

**Comment by uglide** [comment] 2017-09-21 16:10
@jsheely @josefguenther  still cannot reproduce the issue, looks like it is hardware related.

Do you use laptop/pc with integrated Intel graphics? Do you have secondary GPU (amd/nvidia)?
if so, Could you try to install latest driver for  integrated Intel graphics?

**Comment by josefguenther** [comment] 2017-09-21 20:07
@uglide I have an XPS 15 laptop. It has an Nvidia GeForce GTX 1050 graphics card. What is your test machine you are using to reproduce? You may be able to use a standard screen and use Windows scaling features to scale it up (ridiculously large of course) and reproduce?

Edit: I tried scaling my display to 100% (very small) and still have all the same issues. I'm not sure if this confirms your suspicion on hardware or if that means something else.

**Comment by uglide** [comment] 2017-09-21 20:16
@josefguenther I'm testing it on dell laptop with 1080p screen and 2k dell monitor. I've tried different Win10 versions and scale factors (150%,  200%,225%) but it renders just fine. Without cutted off parts, etc
But on my laptop latest Intel graphics driversis installed (not default drivers which comes from windows update)

**Comment by uglide** [comment] 2017-09-21 20:19
@josefguenther yes, more likely its Intel driver issue. Could you double check that you have latest version installed?

**Comment by jschen5** [comment] 2017-10-12 23:01
I'm having this issue too, and I just confirmed that I have the latest version of the Intel HD Graphics 630 installed for my XPS 15 with a 4k screen. The driver version is 21.20.16.4664. Note, this isn't actually the _latest_ driver, it's just the latest one that the XPS 15 supports.

**Comment by olaj** [comment] 2017-10-20 13:48
I ran some updates on my Dell XPS 13 just now and after that it works fine! Version 22.20.16.4771 was installed of the HD drivers.

**Comment by StartMoney** [comment] 2017-11-07 03:11
xps 15 , 1920*1080  
it was no use to update the driver of Intel HD Graphics 630 , 21.20.16.4664. and I download it from dell web site.

**Comment by MartinKolarik** [comment] 2017-11-18 14:09
Starting the program with Nvidia graphics rather than the default integrated Intel graphics fixed the problem for me (XPS 15 with Intel 530 and GTX 960M).

**Comment by josefguenther** [comment] 2017-11-18 19:45
@MartinKolarik how exactly did you do this?

**Comment by MartinKolarik** [comment] 2017-11-18 20:11
@josefguenther http://forums.lenovo.com/t5/image/serverpage/image-id/4817i32CB2A6D7D20EC06/image-size/original?v=mpbl-1&px=-1

**Comment by josefguenther** [comment] 2017-11-18 20:20
@MartinKolarik That worked perfectly, thank you! I was able to set the default graphics card for it and now it runs like a charm. The only remaining issue is on my secondary monitor @ 125% scale, the titlebar on the window and alert windows is still oversized -- just cosmetic.

**Comment by bwarring** [comment] 2017-12-02 22:54
@MartinKolarik Thanks - works great!

**Comment by jsheely** [comment] 2018-01-03 17:47
I got a recent update for the Intel HD Graphics 630 and now the problem is resolved.

![image](https://user-images.githubusercontent.com/1424946/34532473-42e0a81c-f084-11e7-8675-769ceffa301c.png)

**Comment by franciscohdz21** [comment] 2018-02-16 20:44
@jsheely That worked thanks! For anyone trying that, you have to go to Dell website to get the driver. Device manager was no help for me.

**Comment by uglide** [comment] 2018-02-23 15:36
Guys, Could you test new build as-is + with new command line option:
`rdm.exe --rendering-backend software`

https://ci.appveyor.com/project/uglide/redisdesktopmanager/build/0.9.0.732/artifacts

**Comment by uglide** [comment] 2018-02-23 17:17
RDM 0.9.0-3 build looks just fine on Windows 10 with 4k. So I'm closing this issue for now

**Closed as completed by uglide** 2018-02-23 17:17 UTC
Labels: bug, windows

**Comment by MartinKolarik** [comment] 2018-02-23 17:45
@uglide looks good 👍
