### ISSUE TITLE
Cannot view dataframe format in Redis Desktop Manager

### ISSUE THREAD

**Issue by popohoma** [redis/RedisDesktopManager#4775] opened 2020-03-24 05:38 UTC
Hi Team,

I have convert my dataframe to msgpack before persist as key/value pair in Redis, e.g. sample_df.to_msgpack()

However I am unable to view my dataframe in Redis Desktop Manager and it's showing nothing and also no error

Allen

**Comment by uglide** [comment] 2020-03-24 08:19
@popohoma Could you provide some data sample? Which version of RDM do you use?

**Comment by popohoma** [comment] 2020-03-24 08:46
Hi uglide,

Data is simple csv, data with columns that's it.

what I did is following to persist

pool = redis.ConnectionPool(host='A.B.C.D', port=6379, db=6)
r = redis.Redis(connection_pool=pool)

#Set Object
sample_df = pd.read_pickle('c:\\temp\\TestDataFrame.pkl')  # read from current directory
df_bytes = sample_df.to_msgpack()
r.set('flask_cache_Test', df_bytes)

Thanks,

Allen

**Comment by popohoma** [comment] 2020-03-31 05:46
Data is simple csv, data with columns that's it.

what I did is following to persist

pool = redis.ConnectionPool(host='A.B.C.D', port=6379, db=6)
r = redis.Redis(connection_pool=pool)

#Set Object
sample_df = pd.read_pickle('c:\temp\TestDataFrame.pkl') # read from current directory
df_bytes = sample_df.to_msgpack()
r.set('flask_cache_Test', df_bytes)

**Comment by popohoma** [comment] 2020-04-03 19:12
Data is simple csv, data with columns that's it.

what I did is following to persist

pool = redis.ConnectionPool(host='A.B.C.D', port=6379, db=6)
r = redis.Redis(connection_pool=pool)

#Set Object
sample_df = pd.read_pickle('c:\temp\TestDataFrame.pkl') # read from current directory
df_bytes = sample_df.to_msgpack()
r.set('flask_cache_Test', df_bytes)

**Comment by uglide** [comment] 2020-05-26 09:12
Duplicate of #4781

**Closed as completed by uglide** 2020-05-26 09:12 UTC
Labels: bug
