### ISSUE TITLE
question about building from sources in Linux

### ISSUE THREAD

**Issue by lty1024** [redis/RedisDesktopManager#3761] opened 2016-11-03 01:24 UTC
RDM Version: <0.9>
Environment (OS name and version): <ubuntu 16.06>
Redis Server Version: <3.2.5>

Steps to reproduce:

I tried to build it from sources ,and do it as guide.After that, I try to run it as "/usr/share/redis-desktop-manager/bin/rdm" ,but I can't start it .

Actual Result: 
./rdm: /usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5: version `Qt_5' not found (required by ./rdm)
./rdm: /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5: version `Qt_5' not found (required by ./rdm)
./rdm: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by ./rdm)
./rdm: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: version `Qt_5' not found (required by ./rdm)
./rdm: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.6' not found (required by ./rdm)
./rdm: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by ./rdm)
./rdm: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by ./rdm)

thanks

**Comment by ghost** [comment] 2016-11-03 02:15
I also can't start RDM:

./rdm: error while loading shared libraries: libQt5QuickWidgets.so.5: cannot open shared object file: No such file or directory

Already done: sudo apt-get install libqt5concurrent5:i386

**Comment by uglide** [comment] 2016-11-03 10:28
Duplicate of https://github.com/uglide/RedisDesktopManager/issues/3745

**Closed as completed by uglide** 2016-11-03 10:28 UTC
Labels: duplicate, question
