### ISSUE TITLE
saving empty value 

### ISSUE THREAD

**Issue by andykkkk** [redis/RedisDesktopManager#4049] opened 2018-03-17 13:08 UTC
RDM Version: 0.9.1.18<br>
Environment (OS name and version): Kernel: 4.4.0-116-generic x86_64 (64 bit gcc: 5.4.0) Desktop: Cinnamon 3.4.3 (Gtk 3.18.9-1ubuntu3.3) dm: mdm Distro: Linux Mint 18.2 Sonya<br>
Redis Server Version: Redis server v=3.0.7 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=653ddf5423c0ddcc
<br>

Steps to reproduce:

1. Open exist hash key
2. press 'Add Row'
3. Enter new key and value. press 'OK'
4. Reload db or hash key

Expected result: New key with filled value

Actual Result: new key with empty value

![_050](https://user-images.githubusercontent.com/3987030/37555721-a8ed3630-29f4-11e8-90ea-6ce24567abf4.png)
![_051](https://user-images.githubusercontent.com/3987030/37555725-c0395224-29f4-11e8-890a-30402b022d21.png)
![_052](https://user-images.githubusercontent.com/3987030/37555724-bff8c0ba-29f4-11e8-8cc5-ef759034f969.png)
# #

**Comment by uglide** [comment] 2018-04-04 14:07
Duplicate of #4056

**Closed as completed by uglide** 2018-04-04 14:07 UTC
Labels: duplicate
