### ISSUE TITLE
Window Resize Pointer makes it impossible to use Save Button

### ISSUE THREAD

**Issue by kboek** [redis/RedisDesktopManager#4096] opened 2018-04-20 19:31 UTC
RDM Version: 0.9.2.806<br>
Environment (OS name and version): Windows 10<br>
Redis Server Version: N/A<br>

Steps to reproduce:

1. Install RDM on Windows 10 with high resolution (4K) screen

2. Open RDM, open a server select a key

3. Hold mouse pointer over the Save button

Expected result: It's possible to click "Save"

Actual Result: The mouse pointer changes into a resize pointer, to resize the log window

**Comment by jaider** [comment] 2018-04-20 20:11
* Some text are hidden
* Mouse hover is like 10px under the actual buttons

I am using a resolution that is not the recommended one and this could affect the way this app behave?. It also get worse when I change the scale layout to 125% or more...
![image](https://user-images.githubusercontent.com/34106843/39071274-4c034b96-449b-11e8-85a2-72c872d8b260.png)
![image](https://user-images.githubusercontent.com/1471688/39071436-ea79057c-449b-11e8-861d-1a0223cf35e1.png)

**Comment by uglide** [comment] 2018-10-09 07:09
@kboek  I cannot reproduce it on my Windows setup (4K screen + 200% scaling + Win 1803)

Could you provide screenshot?

**Comment by uglide** [comment] 2018-10-09 07:18
I'm closing it for now. If you still see this issue on 1803 or 1809 please reopen it with screenshots and details.

**Comment by kboek** [comment] 2018-10-14 10:15
Since the change that forces MacOS and Windows users to buy a subscription, I haven't bothered to look into this anymore. I don't get paid to fix this bug, but you do now. And as long as the bug's not fixed, it's supposedly still there.

**Comment by uglide** [comment] 2018-10-15 06:29
@kboek I've sent link to latest windows build on your email karel.boek@raskenlund.com
If you still can reproduce issue please provide me more details about your screen setup, win version, etc

**Comment by kboek** [comment] 2018-10-15 07:05
The problem is half-fixed; see attachments. When I hold the mouse pointer over the upper half of the “Save” button, it shows the pointer. When I hover it over the lower half of the button, it shows the resize option. I’m running Win 10 on a Lenovo Yoga 900, with a desktop resolution of 3840 x 2160

**Comment by uglide** [comment] 2018-10-15 07:10
@kboek github does not show attachments, could you forward your email with attachments to my email u.glide@gmail.com

BTW, What scaling factor do you use? 200% or more?

**Comment by uglide** [comment] 2018-10-15 07:23
@kboek What scaling factor do you use? 200% or more?

**Comment by kboek** [comment] 2018-10-15 07:25
125%

**Comment by uglide** [comment] 2018-10-15 07:26
@kboek thanks a lot for all provided information

**Comment by uglide** [comment] 2020-04-09 15:28
Should be fixed now on 2020.0-beta1

**Closed as completed by uglide** 2020-04-09 15:28 UTC
Labels: bug, windows
