### ISSUE TITLE
crashed when scanning too many items

### ISSUE THREAD

**Issue by makkaba** [redis/RedisDesktopManager#4154] opened 2018-07-04 00:54 UTC
RDM Version: <br>0.9.0.76
Environment (OS name and version): <br> window 10
Redis Server Version: <br>4.0 (AWS elasticCache - Redis)

Steps to reproduce:

1. put many records into redis. (about 2000000 records)
2. just open RDM.

Expected result: works fine.

Actual Result: it was hanged. no response.

is there any way to limit scanning amount?

**Comment by uglide** [comment] 2018-08-07 07:38
Duplicate of #3599

**Closed as completed by uglide** 2018-08-07 07:38 UTC
