### ISSUE TITLE
Can not set ssh password on OS X 10.9.3

### ISSUE THREAD

**Issue by messense** [redis/RedisDesktopManager#1965] opened 2014-06-25 10:16 UTC
![image](https://cloud.githubusercontent.com/assets/1556054/3383904/9c593ca4-fc51-11e3-9a67-d661cd1ec711.png)

The UI has some problems.

**Comment by crackfoo** [comment] 2014-06-26 12:00
expand the box and you can see the field

**Comment by messense** [comment] 2014-06-26 13:37
@crackfoo Yes, it worked.

**Comment by uglide** [comment] 2014-06-27 07:00
Duplicate of https://github.com/uglide/RedisDesktopManager/issues/1847

**Closed as completed by uglide** 2014-06-27 07:00 UTC
Labels: duplicate
