### ISSUE TITLE
Ubuntu 0.8.0-15 load nothing...

### ISSUE THREAD

**Issue by gshmu** [redis/RedisDesktopManager#3439] opened 2015-08-13 01:48 UTC
log here 

> 2015-08-13 09:45:47 : Click on tree item: 0
> 2015-08-13 09:45:47 : Connection: 10.7.53.20 > [runCommand] select 0
> 2015-08-13 09:45:47 : Connection: 10.7.53.20 > [runCommand] select 0 -> response received : 0
> 2015-08-13 09:45:47 : Connection: 10.7.53.20 > [runCommand] scan 0 MATCH \* COUNT 10000
> 2015-08-13 09:46:29 : Connection: 10.7.53.20 > [runCommand] scan 0 MATCH \* COUNT 10000 -> response received : 2
> 2015-08-13 09:46:29 : Connection: 10.7.53.20 > [runCommand] scan 56648 MATCH \* COUNT 10000
> 2015-08-13 09:47:14 : Connection: 10.7.53.20 > [runCommand] scan 56648 MATCH \* COUNT 10000 -> response received : 2
> 2015-08-13 09:47:14 : Connection: 10.7.53.20 > [runCommand] scan 139428 MATCH \* COUNT 10000
> 2015-08-13 09:47:41 : Connection: 10.7.53.20 > [runCommand] scan 139428 MATCH \* COUNT 10000 -> response received : 2
> 2015-08-13 09:47:41 : Connection: 10.7.53.20 > [runCommand] scan 73964 MATCH \* COUNT 10000

before update it's ok

**Comment by uglide** [comment] 2015-08-13 02:58
Duplicate of #3436

**Closed as completed by uglide** 2015-08-13 02:58 UTC
Labels: duplicate
