### ISSUE TITLE
saved connections are not updated with default values for new settings

### ISSUE THREAD

**Issue by anapsix** [redis/RedisDesktopManager#3434] opened 2015-08-11 16:23 UTC
After upgrading to version 0.8, existing saved connections continued to work, but was unable to SCAN for keys/lists/etc.
New connection settings were introduced in version 0.8 that did not exist previously.
After the upgrade, those settings values were unset, instead of default values, and effectively became "".
When `keys glob-style pattern` and `namespace separator` are not set properly, the database appears empty, while it is not.

**Workaround:** delete and recreate saved connection

**Comment by uglide** [comment] 2015-08-11 17:50
Duplicate of #3407

**Closed as completed by uglide** 2015-08-11 17:50 UTC
Labels: duplicate
