### ISSUE TITLE
Cannot setup connection

### ISSUE THREAD

**Issue by webmechanics** [redis/RedisDesktopManager#1847] opened 2014-05-18 12:09 UTC
Trying to setup connection via SSH Tunnel, I fill host, port and user fields, and get this error http://cl.ly/image/1e0b1U0j352X. I tried to change IP address to hostname, check "password" checkbox - it doesnt help

**Comment by uglide** [comment] 2014-05-21 17:52
Fixed in 0.7.7

**Closed as completed by uglide** 2014-05-21 17:52 UTC
Labels: bug, osx

**Comment by webmechanics** [comment] 2014-05-24 07:38
thank! where I can download 0.7.7? it still 0.7.6 on a website...

**Comment by uglide** [comment] 2014-05-25 20:16
Hi, I will inform you as soon as Release Candidate is ready.

**Comment by uglide** [comment] 2014-06-10 19:19
@webmechanics 
Please download this night build http://redisdesktop.com/builds/redis-desktop-manager-0.7.7.30.dmg

**Comment by czerasz** [comment] 2016-05-03 17:48
Hi, I can still experience connection issues while using the internal "SSH Tunnel" option in version `0.8.3-120`. The problem is well described [here](http://unix.stackexchange.com/questions/199226/why-ssh-login-works-in-shell-but-fails-in-all-third-parties-via-ssh-tunnel).

System Information:

| Field | Value |
| --- | --- |
| Description | Ubuntu 15.10 |
| Release | 15.10 |
| Codename | wily |

**Comment by Alexand** [comment] 2016-05-11 09:08
Hi Guys, I also experience the same issue. I'm using version `0.8.3-2550` on `OS X 10.11.4`

**Comment by GSailen** [comment] 2018-05-10 13:06
Same issue here, version 0.8.3-2550 on OS X 10.13.4

**Comment by uglide** [comment] 2018-05-10 14:24
0.8.3-2550 is 3 years old release. Please upgrade to latest version (0.9.3).
