### ISSUE TITLE
Crash when reading a redis entry

### ISSUE THREAD

**Issue by betimer** [redis/RedisDesktopManager#3704] opened 2016-09-08 00:29 UTC
RDM Version: 0.8.8.384
Environment (OS name and version): win 10 64 bit
Redis Server Version: <br>

Steps to reproduce:
1. connection to VPN
2. connected to host with db number, and it is successful
3. double click an entry, it loads 5 seconds and crashed

Expected result: 
load and display
Actual Result: 
crash

![2016-09-08 10_26_45-crash reporter](https://cloud.githubusercontent.com/assets/8111748/18333055/095175aa-75af-11e6-8b8a-b2163f7e5218.png)
![2016-09-08 10_25_41-redis desktop manager v 0 8 8 384 not responding](https://cloud.githubusercontent.com/assets/8111748/18333061/11dfc5dc-75af-11e6-8a96-4465f6accd3d.png)
##

**Comment by uglide** [comment] 2016-09-08 06:19
Hello @betimer 
Could you please specify a size of the loaded key? `STRLEN AttendAnywhere.Data.Page.GetControls519` from redis-cli or RDM console

**Comment by betimer** [comment] 2016-09-08 06:45
@uglide  21952

**Comment by uglide** [comment] 2016-09-08 06:53
@betimer Does it crash on any key in your db or only on this particular one?

**Comment by betimer** [comment] 2016-09-08 08:14
@uglide  Not every key, some works fine. Some will display the loading and then crash.

**Comment by uglide** [comment] 2016-09-08 08:16
@betimer Could you please share some test value without sensitive information which leads to chrash?

**Comment by pampy** [comment] 2016-10-13 12:04
Hi @uglide ,
I had the same problem several times in the last days. Now I got a key, which reproducibly crashes RDM.
I tried downgrading from 0.8.8 to 0.8.7, but the problem persists.

![loading](https://cloud.githubusercontent.com/assets/1645025/19348213/16068722-914d-11e6-914f-b472228a6b51.png)

I exported the key for you, using
GET cache:videos:be731e2c1364124420875cc39cf3342f
[videos.txt](https://github.com/uglide/RedisDesktopManager/files/526998/videos.txt)

It would be great if you could take a look at it.
I also got Windows 10 x64, with Redis 2.8.17 running on my local system.

Another information: I tried to import the key from the text file on our linux server (using RDM).
When I paste the content the the "Add new key" window, RDM also crashes.
I guess it could be some problem with the JSON format.

Thank you very much for your help!

**Comment by uglide** [comment] 2016-10-13 12:44
@pampy Thanks for the feedback, I will take a look.

**Comment by ofthesun** [comment] 2017-06-19 22:43
My redis desktop manager crashes as well if I try to change from plain text to JSON. I'm using 0.9.0.559 version

**Comment by oliversalzburg** [comment] 2018-02-05 12:06
I see that long values seem to be truncated now. No crashes so far, much more responsive workflow. Great job.

**Comment by uglide** [comment] 2018-02-06 09:10
@oliversalzburg Could you provide more info on "long values seem to be truncated now" because it shouldn't be truncated :)

**Comment by oliversalzburg** [comment] 2018-02-06 10:56
@uglide I have the view set to **Plain Text**. The key value is truncated after exactly 10K characters. It seems intentional.

**Comment by uglide** [comment] 2018-09-20 16:41
Looks fixed in 0.9

**Closed as completed by uglide** 2018-09-20 16:41 UTC
