### ISSUE TITLE
value window doesn't display binary redis values

### ISSUE THREAD

**Issue by johnkaplantech** [redis/RedisDesktopManager#2228] opened 2014-07-18 17:53 UTC
We have a redis database that stores binary values, and the value window is blank - doesn't display any data.
Examples from redis-cli: 
redis 127.0.0.1:6380> get WN-arya
"\x00\x00\x00\x00\x00\x00\x00\x02"
redis 127.0.0.1:6380> get FI-4832153576
"\x01\x02\x00\x00\x01GE\xc8\xa0\xea\x00\x00\x16\x00\x00\x16\x01\x00\x00\x03\x00\x00\x00\x00\x01\x0b\x00\x00\x00\x01 \x04\xcf\xe8\x19\x00\x03ned\x13\x00\tNed Stark\a\x00\x00\x00\x01 \x04\xcf\xe8\b\x00\x12winter is coming 1\x05 \x04\xcf\xe8T\x00\x00\x01GE\xc8\xa0\xd1U\x00\aR315368"
both of these are displayed as blank values in RDM

Having a binary display similar to 
hexdump -C
would increase the usefulness of the tool to a base level for our app

**Comment by uglide** [comment] 2014-12-13 11:57
Duplicate of #1893

**Closed as completed by uglide** 2014-12-13 11:57 UTC
Labels: enhancement
