### ISSUE TITLE
slow opening 10,000 db server

### ISSUE THREAD

**Issue by afinzel** [redis/RedisDesktopManager#4037] opened 2018-03-02 15:48 UTC
RDM Version: 9.0.684<br>
Environment (OS name and version): Windows / Mac<br>
Redis Server Version: <br>

Steps to reproduce:

1. create a redis server with 10,000 dbs

2. open in Redis Desktop Manager

3. Wait

4. and wait

5. and wait

6. you get hte idea :)

Expected result: 

Loads quickly like it did in the last version

Actual Result: 

It selects all the databases and takes around 30 minutes to access the server. 

Additional:

Not sure if this is a new feature but it would be great to not do the select if there are over x databases.  

Thanks.  Great product btw.

**Comment by uglide** [comment] 2018-03-06 11:07
Duplicate of #3720

**Closed as completed by uglide** 2018-03-06 11:07 UTC
Labels: duplicate
