### ISSUE TITLE
Not fetching data on windows 8.1

### ISSUE THREAD

**Issue by eranhazout** [redis/RedisDesktopManager#3424] opened 2015-08-09 13:07 UTC
The last version 0.8.0 is not really responding on windows 8. 
When you click on db it shows the loading and then nothing happen. 
See the log:
2015-08-09 16:06:57 : Click on tree item: 0
2015-08-09 16:06:57 : Connection: Development > [runCommand] select 0
2015-08-09 16:06:57 : Connection: Development > [runCommand] select 0 -> response received : 0
2015-08-09 16:06:57 : Connection: Development > [runCommand] scan 0 MATCH COUNT 10000
2015-08-09 16:06:57 : Connection: Development > [runCommand] select 0
2015-08-09 16:06:57 : Connection: Development > [runCommand] select 0 -> response received : 0
2015-08-09 16:06:57 : Connection: Development > [runCommand] scan 0 MATCH COUNT 10000 -> response received : 0

**Comment by uglide** [comment] 2015-08-09 13:47
Duplicate of #3407. Please follow instructions in original issue to proceed. Thanks!

**Closed as completed by uglide** 2015-08-09 13:47 UTC
Labels: duplicate
