### ISSUE TITLE
what charset do this tool use?  It can't see chinese language

### ISSUE THREAD

**Issue by airclear** [redis/RedisDesktopManager#1718] opened 2014-04-25 08:25 UTC
if  you try this.
set  test  哈哈

and when you use this tool to see the value , 
it shows wrong ..

**Comment by uglide** [comment] 2014-05-11 13:02
I can't reproduce this bug in RedisDesktopManager 0.7.6. Please provide more details about issue.
![5-11-2014 4-00-53 pm](https://cloud.githubusercontent.com/assets/1655867/2938460/7dc0b41a-d90c-11e3-8e61-d0109f789085.jpg)

**Comment by gshmu** [comment] 2014-07-17 05:25
look this:https://clbin.com/DfztIp.png
![screenshot from 2014-07-17 13 23 57](https://cloud.githubusercontent.com/assets/1797676/3609123/b0f064f8-0d72-11e4-914d-bd3de840a824.png)
line:6  it's me pasted Chinese.
I'm using Ubuntu 14.04x64 RedisDesktopManager 0.7.6

**Comment by gshmu** [comment] 2014-07-17 05:33
@uglide  Can't reproduce, but it's really wrong.
same data on MAC it's OK, but Ubuntu wrong. My system language is English, but Chinese is OK.

**Comment by uglide** [comment] 2014-07-17 06:45
@mhohai Thanks, I will investigate this

**Comment by uglide** [comment] 2015-01-25 09:22
Fixed in 0.8.0

![screenshot from 2015-01-25 11 21 49](https://cloud.githubusercontent.com/assets/1655867/5890999/76a8d2d6-a484-11e4-9d15-c6e8f9c26bc2.png)

**Closed as completed by uglide** 2015-01-25 09:22 UTC
Labels: investigate
