### ISSUE TITLE
Build script error on macOs 10.13.6

### ISSUE THREAD

**Issue by florin-nedelcu** [redis/RedisDesktopManager#4237] opened 2018-09-24 10:04 UTC
RDM Version: 0.9.6 <br>
Environment (OS name and version): macOs High Sierra 10.13.6 <br>

Steps to reproduce:

1. git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.9.6 rdm && cd ./rdm

2. cd ./src && cp ./resources/Info.plist.sample ./resources/Info.plist

3. ./configure

Expected result: 
Build Succes

Actual Result: 
** INSTALL FAILED **

Errors:
note: Using new build systemnote: Planning buildnote: Using build description from disk
warning: no debug symbols in executable (-arch x86_64)
error: unable to create symlink at '/Users/florin/Documents/rdm/build/gbreakpad/Products/Release/crash_report_sender.app'
note: Using new build systemnote: Planning buildnote: Using build description from disk
** INSTALL FAILED **

**Comment by uglide** [comment] 2018-09-24 13:23
Duplicate of #4236

**Closed as completed by uglide** 2018-09-24 13:23 UTC
