### ISSUE TITLE
We need to customize the data analysis!

### ISSUE THREAD

**Issue by Trini7** [redis/RedisDesktopManager#3561] opened 2016-01-06 09:47 UTC
When I put Redis through java serialized data, I can not and intuitive access to relevant data, we need to customize the data analysis!

**Comment by uglide** [comment] 2016-01-06 15:49
Hello @Adar-w 
Could you please describe what exactly do you need in RDM?

**Comment by Trini7** [comment] 2016-01-07 01:45
![image](https://cloud.githubusercontent.com/assets/12758600/12160084/67a9c5d2-b523-11e5-9d95-28fd9e9e1c44.png)

**Comment by Trini7** [comment] 2016-01-07 01:46
Thank you.

**Comment by uglide** [comment] 2016-01-09 13:14
Duplicate of #3534

**Closed as completed by uglide** 2016-01-09 13:14 UTC
Labels: question
