### ISSUE TITLE
Proxy exception non supported on 0.9.x

### ISSUE THREAD

**Issue by rexave** [redis/RedisDesktopManager#4065] opened 2018-03-28 11:20 UTC
RDM Version: 0.9.1.771 
Environment (OS name and version): Win 10 pro x64
Redis Server Version: 3.2

**Steps to reproduce:**

1. Define proxy in IE with host and port
2. Add exception on a DNS suffix like `*.mycompany`
3. Connect to a remote host by DNS : `myserver.mycompany` with password and security "none"

**Expected result:** 

Connexion successful

**Actual Result:** 

Error :
```
2018-03-28 13:13:37 : App log init: OK
2018-03-28 13:13:45 : Connection: Cancel running commands
2018-03-28 13:13:45 : Connection: Disconect on error: Connection error: The proxy type is invalid for this operation
2018-03-28 13:13:45 : Connection: DEV4 > connection failed
```

If i disable the proxy in IE, the connexion is successful

**Comment by uglide** [comment] 2018-04-04 14:31
Duplicate of #3841

**Closed as completed by uglide** 2018-04-04 14:31 UTC
Labels: duplicate
