### ISSUE TITLE
DoubleClick key error

### ISSUE THREAD

**Issue by j7252008** [redis/RedisDesktopManager#4119] opened 2018-05-11 01:59 UTC
RDM Version: 0.9.999 <br>
Environment (OS name and version):  win7<br>
Redis Server Version: <br>

Steps to reproduce:

1. ...add a new key, any type

2. ...doubleclick key once or more

3. ...

Expected result: run normal

Actual Result:  program occurred an error "Assert objectRef == 0"

**Comment by uglide** [comment] 2018-08-06 14:19
Duplicate of #4059

**Closed as completed by uglide** 2018-08-06 14:19 UTC
Labels: duplicate
