### ISSUE TITLE
GUI layout issues with high DPI monitors

### ISSUE THREAD

**Issue by ssirthomas** [redis/RedisDesktopManager#2506] opened 2014-09-10 03:43 UTC
I am using a new Dell with a high DPI screen - the gui for the redis desktop manager does not scale cleanly and the Add Connection dialog is very condensed.  Makes it difficult to use.

![image](https://cloud.githubusercontent.com/assets/6003226/4212379/5794910e-389c-11e4-879d-8838c1043777.png)

**Comment by uglide** [comment] 2015-07-30 13:58
@fuzzycactus Unfortunatly I don't have testing environment with Windows and high DPI display. That's why I will move this issue to 1.0.0 milestone

**Comment by ghost** [comment] 2015-09-02 19:23
Hi guys, I love to help you by testing as I do have a high DPI display. Let me know how can I support you

**Comment by uglide** [comment] 2015-09-03 07:40
Hello @didebeach
Detailed description for this bug will be very helpful! (more screenshots in 100% 125% and 150%)

**Comment by ghost** [comment] 2015-09-03 16:08
150% and lower is better, 150 and bigger until 250% is worst
![150_percent](https://cloud.githubusercontent.com/assets/7933457/9663786/8431d94e-5266-11e5-9329-157592ef2b0e.png)
![200_percent](https://cloud.githubusercontent.com/assets/7933457/9663788/86298fbc-5266-11e5-9aa4-0eb6e6b680c8.png)
![250_percent](https://cloud.githubusercontent.com/assets/7933457/9663797/8e143d3a-5266-11e5-861d-82976f200d0b.png)

the problem is the tab size on the right size and the tree distance on the left side.

if you have a version that I can try out or just a piece of code that you like that I test for you please let me know.

Coming from a c# background but can't help on C++ :-(

**Comment by ssirthomas** [comment] 2015-09-04 21:29
Here are some screenshots for mine, I’m not using percentages, rather, the cumbersome “smaller/larger” scale.  Here is the main window + add connection.

hope it helps.

From: Dirk Decher
Sent: ‎Thursday‎, ‎September‎ ‎03‎, ‎2015 ‎12‎:‎08‎ ‎PM
To: uglide/RedisDesktopManager
Cc: fuzzycactus

150% and lower is better, 150 and bigger until 250% is worst
 150_percent 
 200_percent 
 250_percent 

the problem is the tab size on the right size and the tree distance on the left side.

if you have a version that I can try out or just a piece of code that you like that I test for you please let me know.

Coming from a c# background but can't help on C++ :-(

**Comment by vaidotasstankus** [comment] 2015-10-12 17:35
@fuzzycactus none of your screenshots are visible

**Comment by uglide** [comment] 2016-02-11 10:27
With Qt 5.6 fix for this issue is trivial and will be released in 0.8.4 release

**Comment by jonathansampson** [comment] 2016-03-01 21:39
I too am facing this issue on a Surface Book.

![image](https://cloud.githubusercontent.com/assets/815158/13442753/9c0972dc-dfb2-11e5-8810-6d698852fce1.png)

**Closed as completed** 2016-03-10 08:29 UTC
Labels: bug

**Comment by markybry** [comment] 2017-12-06 09:54
Any progress?

**Comment by markybry** [comment] 2017-12-06 09:55
Why is this issue closed when it hasn't been resolved? Duplicate is closed too.

**Comment by uglide** [comment] 2017-12-06 12:35
@markybry 0.9 branch looks ok on hidpi screens, except #3876

If you see any issues please open new issue with description and screenshots.
