### ISSUE TITLE
rdm 0.9 import/export function missing?

### ISSUE THREAD

**Issue by getpool** [redis/RedisDesktopManager#4158] opened 2018-07-08 01:20 UTC
rdm 0.9 import/export function missing?

**Comment by uglide** [comment] 2018-08-07 07:33
@getpool Do you mean connections import/export? or something else?

**Comment by getpool** [comment] 2018-08-08 15:50
It is said to be the import and export of the database. For example: db0 import and export, or "table" content under db0 for separate export

**Comment by uglide** [comment] 2018-08-27 09:05
Duplicate of #58

**Closed as completed by uglide** 2018-08-27 09:05 UTC
Labels: duplicate
