### ISSUE TITLE
can add a features for folding path if the uniq children node ?

### ISSUE THREAD

**Issue by ystyle** [redis/RedisDesktopManager#3878] opened 2017-08-07 03:47 UTC
RDM Version: 0.9
Environment (OS name and version): All
Redis Server Version: All

Steps to reproduce:

1.  can add a features for folding path if the uniq children node ? like this: 
![](http://osloqpukl.bkt.clouddn.com/201717071143-a.png)

Expected result: 
![](http://osloqpukl.bkt.clouddn.com/201717071143-a.png)

Actual Result:

**Comment by uglide** [comment] 2017-08-11 06:48
Thanks for idea

**Comment by uglide** [comment] 2020-06-10 08:01
Duplicate of #3613

**Closed as completed by uglide** 2020-06-10 08:01 UTC
Labels: enhancement
