### ISSUE TITLE
Console select where db is 10 or over fails

### ISSUE THREAD

**Issue by anoordende** [redis/RedisDesktopManager#3339] opened 2015-04-16 09:54 UTC
Using the console, the select command on a db index 10 or over, deducts 10 from the selected db:

servername:0>select 12
OK
servername:2>

select 10 returns db 0, select 11 returns db 1, select 12 returns db 2, etc.

**Comment by uglide** [comment] 2015-04-16 10:05
Duplicate of #3332

**Closed as completed by uglide** 2015-04-16 10:05 UTC

**Comment by uglide** [comment] 2015-04-16 10:06
I recommend using [0.7.9](http://redisdesktop.com/download#beta) instead of old 0.7.6

**Comment by anoordende** [comment] 2015-04-16 10:57
Sorry, I did search for any existing issues but did not find the duplicate, thanks. Just note that 0.7.9 still says "beta" on the homepage, but I'll give it a go.
