### ISSUE TITLE
UI is messed up on Windows 10 in case if scale factor is 200%

### ISSUE THREAD

**Issue by idubinets** [redis/RedisDesktopManager#4172] opened 2018-07-23 08:28 UTC
RDM Version: 0.9.3.8
Windows 10<br>
Steps to reproduce:

1. Go to the display configuration and change scale factor to the 200%

2. start RDM

3. Open window to setup new connection

![image](https://user-images.githubusercontent.com/2304959/43065779-8b3e959e-8e6b-11e8-8515-7c283ff8f81a.png)

My configuration example
![image](https://user-images.githubusercontent.com/2304959/43065844-b6c49808-8e6b-11e8-8692-374b832e6f22.png)

**Comment by uglide** [comment] 2018-08-02 10:02
Duplicate of #4123

**Closed as completed by uglide** 2018-08-02 10:02 UTC
