### ISSUE TITLE
Text Not visible and Mouse pointer clicks at the wrong elements

### ISSUE THREAD

**Issue by PriyankaGirase** [redis/RedisDesktopManager#3972] opened 2018-01-30 20:44 UTC
RDM Version: <br>
Environment (OS name and version): <br>
Redis Server Version: <br>

Steps to reproduce:

1. ... Redis Desktop manager

2. ... View the first screen

Expected result: 

Actual Result: 
![image](https://user-images.githubusercontent.com/2830057/35590276-3034041a-05bb-11e8-850d-4e45aafde523.png)
![image](https://user-images.githubusercontent.com/2830057/35590329-6169bfa2-05bb-11e8-9e84-349f38ef4940.png)

**Comment by uglide** [comment] 2018-02-06 09:14
Duplicate of https://github.com/uglide/RedisDesktopManager/issues/3876

**Closed as completed by uglide** 2018-02-06 09:14 UTC
Labels: duplicate
