### ISSUE TITLE
Nothing works but can connect to redis cluster

### ISSUE THREAD

**Issue by alaksmana** [redis/RedisDesktopManager#4894] opened 2020-09-10 04:31 UTC
**Describe the bug**
Using the RDM Redis Console only returns Connected. And no values or anything returned back.

**To Reproduce**
1. Connect to redis
2. Click on Redis Console
3. type CLUSTER INFO or KEYS *whatever*
4. See returned "Connected"

**Expected behavior**
See the cluster info or list of keys matching pattern

**Screenshots**
<img width="264" alt="Screen Shot 2020-09-10 at 11 28 58" src="https://user-images.githubusercontent.com/19373994/92681852-fcaba380-f358-11ea-85c1-55286f167714.png">

**Environment (please complete the following information):**
 - OS & version: Mac 10.15.6
 - Redis-Server version 5.0.5

**Additional context**

**Comment by uglide** [comment] 2020-09-10 10:18
Duplicate of #4885
Fix will be published soon as part of 2020.3 release

**Closed as completed by uglide** 2020-09-10 10:18 UTC
Labels: bug
