### ISSUE TITLE
display err in windows edition

### ISSUE THREAD

**Issue by ddonline** [redis/RedisDesktopManager#4105] opened 2018-04-27 07:53 UTC
RDM Version: 0.9.2.806
Environment (OS name and version): windows 10 pro 10.0.16299
Redis Server Version: 3.2.10

Steps to reproduce:

1. open the software

2. connect redis server

3. select a db with keys

4.enable live update

5.wait for a minite

6.show more keys (id db i only have 3 keys)

Expected result: show 3 keys

Actual Result: show more keys whitch have same name
![tim 20180427154206](https://user-images.githubusercontent.com/16586818/39351057-c9b811e2-4a32-11e8-9c23-280725610823.png)
![tim 20180427155437](https://user-images.githubusercontent.com/16586818/39351185-4d1c85ae-4a33-11e8-899d-f73c1ee120fa.png)

**Comment by uglide** [comment] 2018-05-04 14:33
Duplicate of #3995

**Closed as completed by uglide** 2018-05-04 14:33 UTC
