### ISSUE TITLE
A key with a name of Develop:el:auth.login.error is presented in tree incorrectly

### ISSUE THREAD

**Issue by jficarapi** [redis/RedisDesktopManager#3673] opened 2016-08-11 17:43 UTC
RDM Version: 0.8.7.322 <br>
Environment (Windows 10.0.14393 ): <br>
Redis Server Version: 3.0<br>

Steps to reproduce:
1. Add a key with the following name: Develop:el:auth.login.error 
2. Connect to the Redis server using Redis Desktop Manager
3. Expand the tree and observe that the tree shows as follows
   Develop->Devel

Expected result: 
It should be presented as
Develop->el

Actual Result: 
Develop->Devel
![incorrecttreerepresnetation](https://cloud.githubusercontent.com/assets/14874295/17598641/70f7b422-5fc9-11e6-9087-4ff0207a59d8.png)

**Comment by uglide** [comment] 2016-08-16 09:54
@jficarapi Thanks for the bug report. It's duplicate of #3666

**Closed as completed by uglide** 2016-08-16 09:54 UTC
Labels: duplicate
