### ISSUE TITLE
Sorted sets: Integer scores are treated as float

### ISSUE THREAD

**Issue by halaei** [redis/RedisDesktopManager#3537] opened 2015-11-18 13:20 UTC
In redis desktop manager Scores in sorted set are shown as float, but they really are integer, e.g. they can be linux timestamp

The real score: 1447852714. What desktop manager shows: 1.44785e+09

**Comment by uglide** [comment] 2015-11-18 13:25
Duplicate of #3518

**Closed as completed by uglide** 2015-11-18 13:25 UTC
Labels: duplicate

**Comment by halaei** [comment] 2015-11-18 13:28
Great. Thanks. I didn't find that issue. Sorry to bother.

**Comment by uglide** [comment] 2015-11-18 13:29
@halaei np, thanks for the feedback!
