### ISSUE TITLE
delete multi keys

### ISSUE THREAD

**Issue by snspro** [redis/RedisDesktopManager#3545] opened 2015-11-27 08:08 UTC
i hope the development can improve a feature, which allow user can delete multi key or group of keys have same prefix on the left panel by right click on the group keys and select delete

**Comment by uglide** [comment] 2015-11-27 08:57
@snspro it's duplicate of #89
If you really need this feature - please [add donation to #89 via bountysource](https://www.bountysource.com/issues/1339209-delete-namespaces-from-db)

**Closed as completed** 2015-11-27 08:57 UTC
Labels: duplicate
