### ISSUE TITLE
RDM can't connect through proxy server

### ISSUE THREAD

**Issue by amartillo** [redis/RedisDesktopManager#4093] opened 2018-04-13 11:05 UTC
RDM Version: 0.9.1.771<br>
Environment (OS name and version): Windows 10 Enterprise version 1703<br>
Redis Server Version: 3.2.7<br>

Steps to reproduce:

1. Create a connection to an Azure Redis cache:
mycache.redis.cache.windows.net
Port 6380
Security: SSL

2. Click "Test Connection"

3. A dialog says "Can't connect to redis-server" and in the output it says:
2018-04-13 13:02:46 : Connection: Cancel running commands
2018-04-13 13:02:46 : Connection: Disconect on error: Connection error: Proxy denied connection
2018-04-13 13:02:46 : Connection: MyCache > connection failed

Expected result: It worked in Windows 7 so it should work in Windows 10 as well

Actual Result: It seems like RDM can't connect through our proxy server in Windows 10. Our Windows configuration uses a PAC script for proxy connection. I have looked for separate proxy server settings in RDM but can't find any.

How can I make RDM connect to our proxy using the PAC script, alternatively set a proxy server address directly in RDM?

**Comment by uglide** [comment] 2018-04-13 11:25
Duplicate of #3841

**Closed as completed by uglide** 2018-04-13 11:25 UTC
