### ISSUE TITLE
Crashes when opening record with 3108 items

### ISSUE THREAD

**Issue by barrychapman** [redis/RedisDesktopManager#4134] opened 2018-06-02 03:29 UTC
RDM Version: 0.9.3.817<br>
Environment (OS name and version): Windows 10 Pro<br>
Redis Server Version: 4.0.9<br>

Steps to reproduce:

1. Database db0 has 3108 items in it

2. Clicking on it causes it to start loading

3. Finally crashes with an error 'Response Entity too Large'

![image](https://user-images.githubusercontent.com/152958/40869984-7923abba-65f3-11e8-9df8-44e4cd40178e.png)

Expected result: See the records in db

Actual Result: crashes, down like a sack of potatoes

**Comment by uglide** [comment] 2018-09-20 16:37
Looks like duplicate of #3599

**Closed as completed by uglide** 2018-09-20 16:37 UTC
