### ISSUE TITLE
RDM crashes in Windows 7

### ISSUE THREAD

**Issue by win32nipuh** [redis/RedisDesktopManager#3373] opened 2015-06-22 15:57 UTC
I run the current version of RDM on W7. Sometimes it crashes. That is piece of log:

2015-06-22 16:09:14,325 INFO  [default] Connection: LocalRedis > [runCommand] select 0
2015-06-22 16:09:14,326 INFO  [default] Connection: LocalRedis > [runCommand] select 0 -> response received : 0
2015-06-22 16:09:14,327 INFO  [default] Connection: LocalRedis > [runCommand] scan 0 MATCH \* COUNT 10000 -> response received : 2
2015-06-22 16:09:18,600 INFO  [default] Connection: LocalRedis > [runCommand] type user:1000
2015-06-22 16:09:18,601 INFO  [default] Connection: LocalRedis > [runCommand] type user:1000 -> response received : 0
2015-06-22 16:09:18,607 INFO  [default] Connection: LocalRedis > [runCommand] ttl user:1000
2015-06-22 16:09:18,608 INFO  [default] Connection: LocalRedis > [runCommand] ttl user:1000 -> response received : 0
2015-06-22 16:09:18,615 INFO  [default] Connection: LocalRedis > [runCommand] HLEN user:1000
2015-06-22 16:09:18,616 INFO  [default] Connection: LocalRedis > [runCommand] HLEN user:1000 -> response received : 0
2015-06-22 16:09:18,747 INFO  [default] Connection: LocalRedis > [runCommand] select 0
2015-06-22 16:09:18,747 INFO  [default] Connection: LocalRedis > [runCommand] select 0 -> response received : 0
2015-06-22 16:09:18,754 INFO  [default] Connection: LocalRedis > [runCommand] HSCAN user:1000 0 COUNT 10000
2015-06-22 16:09:18,759 INFO  [default] Connection: LocalRedis > [runCommand] HSCAN user:1000 0 COUNT 10000 -> response received : 2
2015-06-22 16:09:23,752 FATAL [default] CRASH HANDLED; Application has crashed due to [SIGSEGV] signal
2015-06-22 16:09:23,754 WARN  [default] Aborting application. Reason: Fatal log at [..\3rdparty\easyloggingpp\src\easylogging++.h:5573]

**Comment by uglide** [comment] 2015-06-23 09:25
@win32nipuh 
Hello, thank you for the feedback!
Could you please add comments for crash via crash reporter in an appropriate GitHub issue?

**Comment by win32nipuh** [comment] 2015-06-23 09:32
привет!
Не совсем понятно, что и где я могу  добавить? плз, напиши подробнее ;-)
Или здесь напиши. 
Я заметил, что это происходит на большом наборе, я генернул set и hash по 100 000 элементов, вот при попытке открыть один из них и рушится.

Слава Україні!

**Comment by uglide** [comment] 2015-06-23 09:43
Привет,
Если ты используешь билд, а не собираешь все самостоятельно из исходников, то у тебя после падения rdm.exe должен запускаться крашрепортер. Этот репортер отправляет дамп и выдает ссылку на баг на гитхабе, в котором можно отписаться по поводу случившегося (пример - https://github.com/RedisDesktop/rdm-debug-symbols/issues/35)

Героям Слава!

**Comment by win32nipuh** [comment] 2015-06-23 10:04
1. Ставил инсталлятором, не строил сам
2. Там так, сейчас повторил:
   хожу в дереве по базе, по set, hash  и пр. ключам.
   И в один момент, став на рут - падает.
3. После падения ничего crashrepoter сам не запускается и ничего не делает.

![rdm_crash](https://cloud.githubusercontent.com/assets/5189614/8303699/ee81ea96-199f-11e5-95b4-d8b014a5f4d8.png)

**Comment by uglide** [comment] 2015-06-23 10:06
ок, спасибо. Попробую воспроизвести.

**Comment by win32nipuh** [comment] 2015-06-23 10:44
That is my db on what it can be reproduced:
(Rename this file to .rar and unpack)

![dump_rename_to_rar](https://cloud.githubusercontent.com/assets/5189614/8304379/7d751962-19a5-11e5-9285-bab4c3f4b630.jpg)

**Comment by uglide** [comment] 2015-06-23 10:45
Thanks!

**Comment by uglide** [comment] 2015-07-21 06:28
@win32nipuh Please try this build on Windows http://redisdesktop.com/builds/redis-desktop-manager-0.7.9.821.exe

**Comment by uglide** [comment] 2015-07-25 12:38
@win32nipuh Can you confirm that this issue was fixed in the latest WIndows build?

**Comment by win32nipuh** [comment] 2015-07-25 16:05
Hi, I can check it in some days and let you know.

**Comment by uglide** [comment] 2015-07-25 16:18
@win32nipuh ok, thanks!

**Comment by uglide** [comment] 2015-07-30 09:04
@win32nipuh Could you confirm that bug was fixed in latest builds?

**Comment by uglide** [comment] 2015-07-30 09:15
I cannot reproduce this issue with latest builds on Windows. So I will close it.

**Closed as completed by uglide** 2015-07-30 09:15 UTC
Labels: bug, Critical
