### ISSUE TITLE
the realese 0.9.1.771 can not change the hash type data's value.

### ISSUE THREAD

**Issue by ray-yuruisoft** [redis/RedisDesktopManager#4061] opened 2018-03-26 10:16 UTC
RDM Version: 0.9.1.771<br>
Environment (OS name and version): win 7 64bit sp1<br>
Redis Server Version: 3.2.100<br>

Steps to reproduce:

1. it's OK to connect Redis DB. And OK to create a hash  via inputing "hmset mytesthash field1 Hello field2 world" in command line.But,i can't create hash's value in the RDM.

2. In RDM,when i choose the hash key which could be like myTestHash,i can change the key 'field1' to be 'field1Another',but the value 'world' could not be changed.

3. When i change the value 'world' to 'worldPlus',i click the button 'save',Then 'worldPlus' rechange to 'world'.

Expected result: the value change can use

Actual Result:

**Comment by coolqingcheng** [comment] 2018-04-04 13:39
I and you the same bug

**Comment by uglide** [comment] 2018-04-04 14:04
Duplicate of #4056

**Closed as completed by uglide** 2018-04-04 14:04 UTC
Labels: duplicate
