### ISSUE TITLE
Cluster mode always Loading key:xxxxx form db x

### ISSUE THREAD

**Issue by RevisitMoon** [redis/RedisDesktopManager#4920] opened 2020-10-14 12:42 UTC
In the cluster mode some values ​​are loaded normally and some values ​​always show that they are loading why?

can't load
![image](https://user-images.githubusercontent.com/23206063/95989269-9dabe380-0e5c-11eb-98fe-74cbeb7bc7b2.png)

can load
![image](https://user-images.githubusercontent.com/23206063/95989369-c0d69300-0e5c-11eb-92f8-86cf5d74ec59.png)

redis server version: 5.0.0
redisDesktopManager version: 2020.4
server: centos 8

use: Mac OS 10.15.6

**Comment by uglide** [comment] 2020-10-15 15:15
@RevisitMoon most likely you haven't updated qredisclient subrepo this is looks like duplicate of older fixed issue

**Comment by RevisitMoon** [comment] 2020-10-15 15:38
> @RevisitMoon most likely you haven't updated qredisclient subrepo this is looks like duplicate of older fixed issue

Thank you. I'll try to update it and try again.

**Closed as completed** 2020-10-20 18:39 UTC
Labels: bug
