### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by halaei** [redis/RedisDesktopManager#3944] opened 2017-12-15 21:48 UTC
RDM Version: Latest compiled from source
Environment (OS name and version): Ubuntu 17.10
Redis Server Version: irrelevant

Steps to reproduce:

1. Open rdm in a display with resolution 3840x2160 (scale 200%)

Expected result: Things should have been rendered as anyone expect. Text should be scaled, ...

 Result: look at the screenshot. Texts are too small. Texts on the buttons and tabs are cropped.
![screenshot from 2017-12-16 01-15-50](https://user-images.githubusercontent.com/7089140/34061793-f25732c8-e1fe-11e7-915c-72b4a0880a1e.png)

**Comment by uglide** [comment] 2017-12-22 10:25
Duplicate of #3945

**Closed as completed by uglide** 2017-12-22 10:25 UTC
