### ISSUE TITLE
Value contains zero-bytes ("\x00") can not be displayed correctly

### ISSUE THREAD

**Issue by tevino** [redis/RedisDesktopManager#1893] opened 2014-06-18 06:04 UTC
Version: 0.7.6
Environment: OS X 10.9.3
Redis Server Version: 2.8.11

In redis-cli do:
    > SET test "123\x00456"
or 
    > SET test "123"
    > SETRANGE test 4 "456"

The value of `test` is then displayed as `123` in RedisDesktopManager, it seems that RedisDesktopManager treats `\x00` as **the end of that value**.

**Comment by uglide** [comment] 2015-03-09 10:30
Duplicate of #1738

**Closed as completed by uglide** 2015-03-09 10:30 UTC
Labels: enhancement
