### ISSUE TITLE
redis-desktop-manager-0.8.8.384 takes 13 minutes to load while version 0.7.6 loads the same in seconds

### ISSUE THREAD

**Issue by Anthony-Kearns** [redis/RedisDesktopManager#3810] opened 2017-02-24 10:37 UTC
RDM Version: 0.8.8.384
Environment (OS name and version): Windows 7
Redis Server Version: See below information about server and  keys

info
# Server
redis_version:2.6.9
redis_git_sha1:00000000
redis_git_dirty:0
redis_mode:standalone
os:Linux 2.6.32-642.6.2.el6.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.1.2
process_id:1840
run_id:20b217e3b00932688633ac6e23ac16115d018154
tcp_port:6380
uptime_in_seconds:8523279
uptime_in_days:98
lru_clock:1992595

# Keyspace
db0:keys=137,expires=0
db6:keys=370,expires=0
db8:keys=2151,expires=0
db20:keys=479,expires=0
db21:keys=50,expires=0
db29:keys=1,expires=0
db41:keys=262,expires=0
db74:keys=8,expires=0
db99:keys=554,expires=0
db107:keys=1580,expires=0
db132:keys=1,expires=0
db133:keys=2,expires=0
db134:keys=1,expires=0
db135:keys=1,expires=0
db136:keys=1,expires=0
db137:keys=1,expires=0
db248:keys=63,expires=0
db251:keys=69,expires=0
db255:keys=1401,expires=0
db343:keys=1,expires=0
db345:keys=1,expires=0

Steps to reproduce:

1. Install latest 0.8.8.384 redis desktop manager

2. connect to the Database

3. ...

Expected result: 
database keys and values should load in a reasonable time frame

Actual Result: 
takes 12 minutes for the keys and values to be loaded and version 0.7.6 loaded within seconds

**Comment by uglide** [comment] 2017-03-29 08:28
Duplicate of https://github.com/uglide/RedisDesktopManager/issues/3720

**Closed as completed by uglide** 2017-03-29 08:28 UTC
Labels: duplicate
