### ISSUE TITLE
Package can't be installed on Ubuntu 15.10

### ISSUE THREAD

**Issue by atrauzzi** [redis/RedisDesktopManager#3580] opened 2016-02-01 00:33 UTC
Dependencies don't seem to be lining up correclty.  I can force the install to happen, but then I can't install any new packages because it leaves the system in a broken state.

**Comment by tylerjharden** [comment] 2016-02-02 00:04
+1 also same issue.

The dependency in question for me is `libicu52`

**Comment by uglide** [comment] 2016-02-03 08:56
Duplicate of #3554

**Closed as completed by uglide** 2016-02-03 08:56 UTC
Labels: duplicate
