### ISSUE TITLE
0.9 Memory leaks

### ISSUE THREAD

**Issue by shizenghua** [redis/RedisDesktopManager#3873] opened 2017-07-27 06:00 UTC
In the win10 system, 0.9 memory has been growing. 
As long as I click with the mouse, the memory will grow a little. 
I just found eating 2G memory, I changed back to the 0.8 version.

**Comment by katuknow** [comment] 2017-09-15 10:41
Duplicate of #3855

**Closed as completed by katuknow** 2017-09-15 10:41 UTC
Labels: duplicate
