### ISSUE TITLE
Non ascii node name is garbled in tree view

### ISSUE THREAD

**Issue by truebit** [redis/RedisDesktopManager#3744] opened 2016-10-11 02:26 UTC
- RDM Version: 0.8.8
- Environment (OS name and version): Mac OS X 10.11, 10.12
- Redis Server Version: not related
#### Steps to reproduce:
1. add following key-value for example:
   set test:测试:test1 test
   set test:测试:test2 test
2. open in RDM to see the tree view
#### Expected result:

 "测试" is should be displayed.
#### Actual Result:

 "测试" is garbled

**Comment by uglide** [comment] 2016-10-21 09:36
Duplicate of #3695

**Closed as completed by uglide** 2016-10-21 09:36 UTC
Labels: duplicate
