### ISSUE TITLE
Keys are not loading - MacOs

### ISSUE THREAD

**Issue by suqram** [redis/RedisDesktopManager#4931] opened 2020-10-24 22:40 UTC
Version: 2020.4.104 (Mac App Store version)
Environment: macOS Catalina 10.15.7 
Redis Server Version: 4.0.14 (Redis for Azure, 3x13GB cluster)

Steps to reproduce:
1. Open RDM
2. Connect to Redis cluster (problem seems to only exist in cluster environments)
3. Try to open a key (message pack compressed rows)

Expected result: Display of key rows and values

Actual Result: Screen says: Loading key: <name of key> from db0, but nothing more happens.

Log excerpt: 
<img width="546" alt="Screenshot 2020-10-25 at 00 36 55" src="https://user-images.githubusercontent.com/16638612/97095002-7625f980-165a-11eb-8a94-11e87cc3ea29.png">

**Comment by suqram** [comment] 2020-10-24 22:47
Seems to be a duplicate of #4920, but this is with the Mac AppStore version

**Comment by uglide** [comment] 2020-10-28 12:52
@suqram thanks for the bug report, most likely it is duplicate of #4920 but we currently have issues with publishing new builds to AppStore (build is stuck under review) so if possible please try latest DMG build from our website (start free trial) https://rdm.dev

**Comment by uglide** [comment] 2020-11-03 10:49
@suqram Could you please test latest 2020.5.137 build from AppStore?

**Comment by suqram** [comment] 2020-11-03 19:16
Sorry for the delay. I have tested the new release in Mac AppStore now, and it sort of solved the issue, but others appeared instead. I will mention them here, but feel free to direct me to open new issues.
MessagePack disappeared from the View as list. And (and this only happens when connected to cluster) when I open a folder and select the first key, RDM gets stuck in a loop (see image) and only way to exit RDM is to use force close.
<img width="719" alt="RDM" src="https://user-images.githubusercontent.com/16638612/98030426-4375c100-1e11-11eb-8ecb-b81329b3ecb5.png">

**Comment by uglide** [comment] 2020-11-04 09:29
@suqram thanks for the feedback. Could you please provide a screenshot of the "View as" dropdown?

**Comment by suqram** [comment] 2020-11-04 10:26
Here is the dropdown.
<img width="140" alt="Screenshot 2020-11-04 at 11 25 11" src="https://user-images.githubusercontent.com/16638612/98100028-980c5100-1e90-11eb-837c-5c5205cc8a28.png">
From the log file:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/16638612/98112454-892e9a00-1ea2-11eb-8729-d2fa49a35b1f.png">

**Comment by uglide** [comment] 2020-11-16 16:26
@suqram Could you try preview build from the website rdm-2020.6.267.dmg?

It includes a fix for the problem you described above.

**Comment by uglide** [comment] 2020-11-30 11:45
@suqram Fixed version was released to App Store. Please let me know if you still experience any of the described issues.

**Closed as completed by uglide** 2020-11-30 11:45 UTC
