### ISSUE TITLE
Unable to install RDM on POP!_OS (17.10)

### ISSUE THREAD

**Issue by wout** [redis/RedisDesktopManager#4072] opened 2018-03-31 16:33 UTC
RDM Version: 0.9.1.18
Environment (OS name and version): POP!_OS 17.10 (Ubuntu based)
Redis Server Version: 4.0.1

Steps to reproduce:

`sudo dpkg -i redis-desktop-manager_0.9.1.18_amd64.deb`

Expected result:
Successful installation

Actual Result:
The following packages have unmet dependencies:
  redis-desktop-manager: Depends: libpng12-0 but it is not installable

NOTE: I installed libpng12-0 manually but still getting the error

**Comment by uglide** [comment] 2018-04-04 14:37
Duplicate of #4066

**Closed as completed by uglide** 2018-04-04 14:37 UTC
