### ISSUE TITLE
Support for high resolution screens

### ISSUE THREAD

**Issue by ghost** [redis/RedisDesktopManager#3458] opened 2015-08-29 14:34 UTC
Would be so great, if you can include support for high resolution screens.

**Comment by zam6ak** [comment] 2015-09-01 13:35
+1
On hi res monitors, if you scale the size to 125% or higher, the UI completely breaks...

**Comment by uglide** [comment] 2015-09-01 13:49
Hello @didebeach and @zam6ak 

Unfortunatly I don't have testing environment with Windows and high DPI display. But you can post bounty to this issue and someone with appropriate hardware will fix it.

Duplicate of #2506

**Closed as completed by uglide** 2015-09-01 13:49 UTC
Labels: duplicate
